AlexsLemonade/scpca-portal

client/next.config.js, client/package.json, client/pages/_app.js, client/pages/_error.js, client/yarn.lock
#6 
Adds sentry to the frontend
* installs `@sentry/react`
* adds an `ErrorBoundary` w/ `Error` fallback page
* just the page structure no designs yet
* adds in the nextjs configs for passing through the env vars for sentry to consume
n/a
n/a
=> 6 sentry on frontend initial add

client/.babelrc.js, client/.eslintrc.js, client/.eslintrc.json, client/.prettierignore, client/.prettierrc, client/.storybook/main.js, client/.storybook/preview-head.html, client/.storybook/preview.js, client/jsconfig.json, client/next.config.js, client/package.json, client/pages/_app.js, client/pages/_error.js, client/pages/index.js, client/vercel.json, client/yarn.lock, docker-compose.yml
#8 
* Sets up the docker compose dev environment
* Adds various config files
* Sets up linting and prettier
* adds in vercel config file
* Was able to start everything locally
n/a
=> 8 set up local dev

infrastructure/README.md, infrastructure/api-configuration/api-server-instance-user-data.tpl.sh, infrastructure/api-configuration/environment.tpl, infrastructure/api-configuration/nginx_config.conf, infrastructure/api-configuration/start_api_with_migrations.tpl.sh, infrastructure/api.tf, infrastructure/backend.tf, infrastructure/database.tf, infrastructure/deploy.py, infrastructure/destroy_terraform.py, infrastructure/init_terraform.py, infrastructure/logging.tf, infrastructure/networking.tf, infrastructure/permissions.tf, infrastructure/s3.tf, infrastructure/security.tf, infrastructure/tf_vars/dev.tfvars, infrastructure/tf_vars/prod.tfvars, infrastructure/tf_vars/staging.tfvars, infrastructure/variables.tf
#12 
There's no elasticsearch or SES, but other than that this extremely similar to the infrastructure of the Resources Portal. 
I've successfully curled the `/v1/projects/` endpoint using the elastic IP.
=> Add infrastructure for a dev stack

client/package.json, client/pages/_app.js, client/pages/_document.js, client/src/helpers/applyAll.js, client/src/helpers/applyWhen.js, client/src/theme/anchor.js, client/src/theme/buttons.js, client/src/theme/checkBox.js, client/src/theme/global.js, client/src/theme/heading.js, client/src/theme/icon.js, client/src/theme/index.js, client/src/theme/layer.js, client/src/theme/paragraph.js, client/src/theme/radioButton.js, client/src/theme/select.js, client/src/theme/text.js, client/src/theme/textInput.js, client/yarn.lock
#5 
* adds individual files for grommet theme
* adds grommet-icons for the select dropdown
* wraps app in theme context
Note: will add tabs later as the style has changed and will need assets to make them look right
n/a
n/a
=> 5 grommet theme

api/scpca_portal/config/logging.py
https://github.com/AlexsLemonade/scpca-portal/pull/34
I added some logging and forgot to include this file in that PR.
It works locally, it did before because I already had this file locally, but it still does.
=> Add logging namespace.

.github/workflows/deploy_staging_backend.yml, api/Dockerfile.prod, infrastructure/permissions.tf
#15 
This sets up the github workflow to deploy staging whenever we merge a branch into `dev`. It also fixes a few bugs I ran into along the way.
```
$ curl https://api.staging.scpca.alexslemonade.org/v1/samples/
{"count":1,"next":null,"previous":null,"results":[{"computed_file":1,"project":3,"id":1,"has_cite_seq_data":false,"scpca_sample_id":"SCPCS000109","technologies":"10Xv3","diagnosis":"Neuroblastoma","subdiagnosis":"MYCN non-amplified","age_at_diagnosis":"9","sex":"F","disease_timing":"Initial Diagnosis","tissue_location":"Adrenal Gland","treatment":"treated","seq_units":"cell","additional_metadata":{"COG Risk":"High","Treatment":"treated","IGSS Stage":"4","Primary …
```
=> Staging stack deploys

api/scpca_portal/serializers.py
#54 
I meant to do this and I'm quite surprised the tests passed. I'm still looking into why they did.
I tried the tests again and they did in fact fail. With this change they pass.
=> Make ProjectSerializer inherit correctly.

api/scpca_portal/test/views/test_filter_options.py, api/scpca_portal/views/filter_options.py
N/A it's 500ing in staging
When projects have no samples, they have no diagnses, so split fails because it's being called on `None`. This should avoid that.
I added a unit test which should have been failing and then fixed it. I added it first in a separate commit to make sure.
=> Fix filter options

client/src/components/DonateButton.js, client/src/components/Header.js, client/src/components/Layout.js
N/A
* Adds a Donate button for the header
* Adds an option to show it on the header
* Adds the option when user is on about page to show the donate button on the header
n/a can test when we make the about page
n/a
=> add donate to header

client/.babelrc.js
n/a
* Fixes an issue where the client and server had mismatch attribute values for data-name
* also fixed another issue with data-name not being a valid attribute
n/a
n/a
=> update svgo plugin options

api/scpca_portal/views/filter_options.py, client/.storybook/stories/ProjectSearchFilterPills.stories.js, client/src/api/index.js, client/src/api/resources/options.js, client/src/components/Link.js, client/src/components/ProjectHeader.js, client/src/components/ProjectSearchFilter.js, client/src/components/ProjectSearchFilterPills.js, client/src/components/ProjectSearchResult.js, client/src/contexts/ScPCAPortalContext.js, client/src/helpers/capitalize.js, client/src/helpers/getReadable.js, client/src/pages/projects/index.js, client/src/theme/global.js
#58 
* Adds the browse projects page and the filtering to support that page
n/a works but would work better with more data
=> 58 projects browse page

api/scpca_portal/management/commands/load_mock_data.py, api/scpca_portal/views/project.py, bin/sportal, client/src/api/resources/options.js, client/src/pages/projects/index.js
n/a
* adds a command that creates "realistic" mock data for user testing
* fixes a change on the api for the client `options/projects` -> `project-options`
* client change to make 2 api calls happen async
was able to load data locally
n/a
=> mock data command

client/src/config/privacy-policy.md
n/a
* updates the privacy policy md with changes from yesterday
- update
n/a
=> update privacy policy

client/package.json, client/src/components/DonateButton.js, client/src/components/Download.js, client/src/components/Header.js, client/src/components/ProjectSearchFilter.js, client/src/components/ProjectSearchFilterPills.js, client/src/config/ga.js, client/src/contexts/AnalyticsContext.js, client/src/pages/_app.js, client/src/pages/_document.js, client/src/pages/about/index.js, client/yarn.lock
#95 
* adds `react-ga` package to handle the ga script and initialization
* Adds a `config/ga.js` to define functions for passing events to googleanalytics
* Implements events based on the analytics stragegy docs
* downloads w/ types and filenames
* donate button clicks
* filters being turned on and turned off 
n/a saw the events locally but have yet to see them populate in the dashboard
n/a
=> 95 analytics

.github/workflows/deploy_prod_backend.yml
#100 
Wrong branch name :/ master->main
=> Fix branch name in prod deploy

.github/workflows/deploy_prod_backend.yml
=> Actually deploy to prod for the first time!

client/next.config.js
n/a
fixes to let the production deployment use the production env vars
n/a
n/a
=> prod on main branch

api/scpca_portal/management/commands/load_data.py, api/scpca_portal/test/management/commands/test_load_data.py
N/A Noticed after prod deploy
This was using the wrong file path for the project zip.
=> Set the project zip size correctly.

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
#111 
Close but I forgot I had to run this to get it working. I ran just this step on staging and it worked!
=> Restart nginx after installing new config with certbot enabled.

api/scpca_portal/management/commands/load_data.py, api/scpca_portal/test/management/commands/test_load_data.py
#96 
We've got all the forms, so we release all the data!
Guest reviewer @jaclyn-taroni to confirm the expansion of the whitelist.
I'm relying on unit tests here, but these are minor changes.
=> Expand the whitelist

README.md, api/README.md
N/A I noticed these were omitted.
I added a script without mentioning it in the readme. That was bad but I fixed it. I also added the top level readme since we haven't had one.
y screenshots that illustrate these changes.
=> Add load_data.sh to readme.

infrastructure/deploy.py
=> Pass additional secrets through terraform.

infrastructure/api-configuration/load_data.tpl.sh
N/A
Updates the load_data.sh to stay attached and clean up the instance on exit
n/a - did test on staging
n/a
=> load_data script attached and clean up

api/scpca_portal/management/commands/load_data.py
N/A
Adds Gawad to the whitelist of pi's 
n/a
=> add pi gawad + christensen to whitelist

client/src/pages/projects/[scpca_id].js
N/A
Links out the contact user
N/A
=> link contact info email

client/.storybook/data/project.js, client/src/components/ProjectHeader.js
#163
Edited `ProjectHeader.js` and added a new key `downloadable_sample_count` in `.storybook/data/project.js`
=> #163 Support Nondownloadable Samples FE

client/src/components/ProjectSamplesTable.js
Related issue: #163 
Fix the width issue of Download cell for 'Not Available For Download'
Added min width to `<Box>`
N/A
- [ x] Lint and unit tests pass locally with my changes
=> add min width to Box

api/scpca_portal/views/project.py
N/A
* reveres the order of the projects listing page
n/a local
n/a
=> reverse default order

api/scpca_portal/views/project.py, client/src/components/ProjectSamplesTable.js
Deploy new project order to production
=> Deploy to Prod

api/scpca_portal/models/sample.py
#164 
Simplifies the check for adding modalities to the project model.
n/a tested locally
n/a
=> 164 remove extra check for modalities

.github/workflows/lint.yml, api/scpca_portal/models/sample.py
#164 
* fixes a warning about `prettier_lint` not existing
* another attempt at fixing the flake too complex error that isnt showing up locally
n/a reimported a project for validity
n/a
=> 164 - GitHub actions linter

.github/FUNDING.yml
https://github.com/AlexsLemonade/AdminItems/issues/477
Updated the donate link
=> updated sponsor link

api/requirements.txt, api/scpca_portal/migrations/0001_initial.py, api/scpca_portal/models/sample.py
=> Upgrade Django to 3.2 LTS.

api/scpca_portal/models/project.py, api/scpca_portal/test/management/commands/test_load_data.py
=> Add all additional metadata columns at the end.

api/scpca_portal/models/project.py
In order to fix errors during project 9 importing
=> Skip sample if its folder doesn't exist.

client/src/components/Badge.js, client/src/components/Download.js, client/src/components/Footer.js, client/src/components/InfoText.js, client/src/components/Logo.js, client/src/components/Pagination.js, client/src/components/ProjectSearchResult.js, client/src/components/TableFilter.js, client/src/pages/about/index.js, client/src/pages/index.js
#182 
Added basic accessibility for images/icons/form elements
=> 182 Basic Accessibility for images/icons/form elements

client/src/components/DonateButton.js, client/src/config/index.js
#190
Updated donate button links to the new form
- [x ] Lint and unit tests pass locally with my changes
=> 190 Change donate button links to new form

client/src/components/ProjectSamplesTable.js
Make a small refactoring in the initial sort function in ProjectSamplesTable.js
=> Make a small refactoring in the initial sort function in ProjectSamplesTable.js

api/scpca_portal/models/computed_file.py, api/scpca_portal/models/project.py, api/scpca_portal/test/management/commands/test_load_data.py, api/scpca_portal/test/test_utils.py, api/scpca_portal/utils.py
Display all listed versions for project/sample computed files.
#223 
Fixes missed workflow versions for project level computed files
Bugfix (non-breaking change which fixes an issue)
[x] Lint and unit tests pass locally with my changes
[x] I have added tests that prove my fix is effective or that my feature works
=> Populate project's computed files workflow version. 

api/Dockerfile.local, api/requirements/local.txt, api/scpca_portal/config/production.py
Remove gunicorn from the Django config.
Remove new-relic from local env.
=> Fix gunicorn dependency.

api/scpca_portal/views/project.py, client/src/components/ProjectHeader.js, client/src/components/ProjectSamplesTable.js
N/A
Went through the site clearing up any misc issues I found. 
* fixes issue with filtering by modalities
* fixes issue with non-downloadable samples showing a download button
* fixes an issues with modalities tag appearing on the next line
* fixes a sorting issue where the non-downloadable samples were appearing first in the samples table
n/a 
n/a
=> misc bug fixes

infrastructure/api.tf
n/a
We were running out of space when we wanted to run the load data command and replace everything. This change will give us more space so we can still do that.
Also, removes some stray `tab`s
n/a
N/A
=> enlargen block store

client/src/components/DownloadStarted.js
n/a
After refactoring to handle the dynamic details for listing the contents of a download, some logic to show information about the other computed files was not updated and causing errors. This updates that.
n/a loads
n/a
=> Use helper in new component

api/requirements/local.txt
Make it consistent with other dependencies.
=> Set flake8 version explicitly.

client/src/hooks/useHubspotForm.js, client/src/pages/index.js
#173 
Remove persistent thank you for subscribing.
N/A
=> 173 Remove persistent thank you for subscribing

api/scpca_portal/models/computed_file.py, api/scpca_portal/models/project.py, api/scpca_portal/models/project_summary.py, api/scpca_portal/models/sample.py
Get rid of repetitive code. The PR doesn't involve any DB changes.
=> Make models derived from `TimestampedModel`.

api/scpca_portal/templates/readme.md, api/scpca_portal/templates/readme_multiplexed.md
closes #244
Updates readme file for multiplexed data with appropriate info.
I mostly followed the main readme file text, with additions for the multiplexed data file structure and expectations, with links to the appropriate sections of the docs.
All updates to template markdown file.
(documentation update)
I have not tested variable substitution, though these are unchanged from `readme.md`
=> Multiplex readme text

api/Dockerfile.local, api/Dockerfile.prod, api/install_awscli.sh
Run ScPCA API container natively. Change hardcoded architecture to a dynamic one.
=> Determine awscli installation URL based on the container architecture.

api/Dockerfile.local, api/Dockerfile.prod, api/README.md, api/requirements/base.txt, api/scpca_portal/management/commands/load_data.py, api/scpca_portal/models/project.py, api/scpca_portal/test/management/commands/test_load_data.py
Resolves https://github.com/AlexsLemonade/scpca-portal/issues/265
Respect specified `scpca_project_id` and `scpca_sample_id` flags during syncing.
- Move awscli dependency from Docker file to the requirements.
- Update boto3 package version.
- Bump Python version to 3.10
- Fix project_ids/sample_ids related flag names, update the README file.
=> Rework file downloading process.

api/requirements/prod.txt
=> Bump uwsgi version.

api/scpca_portal/models/project.py
Fix downloadable samples count.
=> Fix available samples count.

client/src/config/index.js
n/a
Update multiplex doc links directly to https://scpca.readthedocs.io/en/latest/processing_information.html#multiplexed-libraries
n/a
n/a
=> update multiplex doc link to section

.github/workflows/push.yml
#304 
Update the python version to 3.10 in Github Action workflows to match the change in Dockerfiles.
N/A
=> 304 - Update Python version in Github Action workflows 

.github/PULL_REQUEST_TEMPLATE.md
#2 
Added it as a comment under implementation notes.
=> Add guidelines for getting design input

api/scpca_portal/management/commands/load_data.py
N/A
- Adds Mullighan to the submitter whitelist
N/A
N/A
=> add mullighan to submitter whitelist

infrastructure/api-configuration/api-server-instance-user-data.tpl.sh, infrastructure/api.tf
#315 
- Uses the latest ubuntu 22.04 AMI
- Adds docker install to user-data
- fixes tabs in user-data
- updates apt-get -> apt
n/a
N/A
=> Update API AMI

client/src/components/Layout.js
#318 
Temporarily take the banner down for UX.
A really small update was made to the codebase for UX, thus, add @dvenprasad as the reviewer, thank you @davidsmejia!
Verify the update via localhost.
N/A
=> 318 - Take down ScPCA-nf recruitment Banner

client/src/components/ProjectSamplesTable.js
#328 
**API:** https://api.scpca.alexslemonade.org/v1/projects/SCPCP000009
Added a separator for multiple modalities in the sample table.
=> 328 - Display of multiple modalities in sample table needs separator

api/Dockerfile.local, api/Dockerfile.prod
Optimize API docker images:
- Combine `RUN` commands.
- Use JSON form for `SHELL` and `CMD`.
- Remove static collection from prod `CMD`.
N/A
Tested using dev deploy.
N/A
=> Update ScPCA docker images

api/scpca_portal/models/project.py
Fix pre-commit flake8 error:
```
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for merge conflicts................................................Passed
Check Yaml...............................................................Passed
Flake8...................................................................Failed
- hook id: flake8
- exit code: 1
api/scpca_portal/models/project.py:227:36: E741 ambiguous variable name 'l'
```
N/A
N/A
=> Fix Github pre-commit flake8 error.

.pre-commit-config.yaml, api/scpca_portal/config/production.py, api/scpca_portal/models/project.py, api/scpca_portal/test/factories.py, api/scpca_portal/views/computed_file.py, bin/sportal, infrastructure/deploy.py, infrastructure/destroy_terraform.py, pyproject.toml, setup.cfg
N/A
Re-configure pre-commit flake8 settings:
- Ignore less, use per file ignores.
- Add forgotten `print` instructions check.
Fix line length issues.
Re-order setup.cfg options.
N/A
N/A
N/A
=> Re-configure pre-commit.

infrastructure/deploy.py
NA
Fix staging deploy error - https://github.com/AlexsLemonade/scpca-portal/actions/runs/3584522558/jobs/6031306819
Revert IP address regex.
It didn't match staging (but did match dev).
NA
=> Fix staging deploy

api/scpca_portal/urls.py
N/A
Most of the API links were broken:
- swagger
- redoc
- tos
- readthedocs
- issues
I replaced them with appropriate targets.
N/A
N/A
=> Fix API links

api/scpca_portal/management/commands/load_data.py, api/scpca_portal/models/computed_file.py, api/scpca_portal/test/management/commands/test_load_data.py
Resolves #336 
Add `_processed.rds` support for single cell and multiplexed samples.
NA
NA
=> Add `_processed.rds` support for single cell and multiplexed samples

.gitignore
NA
Add test_data* to .gitignore (ignore local test_data backups as well)
NA
NA
NA
=> Exclude `api/test_data...`.

client/package.json, client/yarn.lock
N/A
Downgraded the eslint version to `7.32.0` to prevent an error during deploy(which was observed locally as well) 
(resource) https://github.com/vercel/next.js/issues/30182
=> Fix - Downgrade the eslint version to 7.32.0 to prevent error

client/package.json, client/yarn.lock
(fix) downgrade the eslint version to 7.32.0(recommended: https://github.com/vercel/next.js/issues/30182)to prevent an error (#349)
=> Fix Vercel deploy

client/package.json, client/yarn.lock
Production Deploy
Deploy teachey/tan whitelist to production
=> Production Deploy

.github/workflows/push.yml
Resolves #359
Update GitHub actions/checkout to v3
Bugfix (non-breaking change which fixes an issue)
NA
NA
=> Update actions/checkout from v2 to v3

api/scpca_portal/management/commands/load_data.py
Resolves #361 
Add pugh to the allowed submitters list
NA
NA
NA
=> Add pugh to allowed submitters

api/scpca_portal/config/common.py, api/scpca_portal/config/production.py, api/scpca_portal/management/commands/load_data.py, api/scpca_portal/test/management/commands/test_load_data.py, infrastructure/api.tf, setup.cfg
NA
Clean up output data for each project once it's processed.
NA
NA
=> Optimize data loading process disk usage

infrastructure/api.tf
#370 
Scales Down the attached volume on the API
Must wait until SCPCP000008 is done being loaded in.
n/a
n/a
=> Scale Down API Volume

api/README.md
Resolves #373 
Add `--cleanup-output-data` clause to the API README.md
N/A
N/A
=> Update API README.md

api/README.md, infrastructure/api.tf
Production Deploy
Scale's up the volume attached to the API
Updates docs
=> Prod Deploy

infrastructure/api.tf
n/a
Processing SCPCP000008 failed again due to lack of space. Bumping this up so we can process everything.
n/a
n/a
=> 350gb volume

client/next.config.js
#391 
- Temporarily sets env vars in next.config.js to 
- built locally
n/a
=> use production env vars for dev and main branch deploys

client/next.config.js
n/a
I need to see what comes out of this, for a staging and production deploy in the build step on vercel.
- debug
n/a
n/a
=> log out VERCEL_GIT_COMMIT_REF

client/next.config.js
#391 
I believe I was able to fix things on the vercel side. This is a PR to test those changes.
- revert
n/a
n/a
=> isProduction on main branch

client/next.config.js
#391 
- that didnt work, need to log this on production now. 
- debug
n/a
n/a
=> Log Vercel Git Commit Ref

client/next.config.js, client/src/config/index.js, client/src/pages/about/index.js
#189 
Added the grants program link to `Learn more about the grants program` on the about page.
@Jen-OMalley, please visit the latest [here](https://scpca-portal-lf6np2snr-ccdl.vercel.app/about), thank you!
=> 189 - Add grants program link on about page

client/src/pages/contribute.js
#389 
Updated the button to read "Complete the Intake Form"
=> (Minor Update 389) Update button text to be 'Complete The Intake Form'

README.md
=> add whitespace

api/requirements/base.txt, api/scpca_portal/models/project.py
Update the way we process sample metadata. Fix the multiplexed metadata tests flakiness.
=> Handle sample metadata in a deterministic manner

client/src/pages/_document.js
ScPCA-admin [#608](https://github.com/AlexsLemonade/ScPCA-admin/issues/608)
Partially reverted back the previously merged PR https://github.com/AlexsLemonade/scpca-portal/pull/180 - replaced the Next.js `Script` component with DOM `<script>` for the hotjar (it won't load with `Script`).
Conformed that the localhost now makes hotjar API request.
=> Add HotJar to ScPCA for tracking

infrastructure/api-configuration/run_command.tpl.sh
Resolves #415 
Use part of constantly available disk space as a container data volume.
=> Attach a persistent data volume to the data loading container

.github/workflows/deploy_prod_backend.yml, .github/workflows/deploy_staging_backend.yml
Migrate to 1password service account.
The failed test cause doesn't seem to be related to the OP (`Error: Node.js Version "14.x" is discontinued and must be upgraded. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.`)
=> Use 1password service account token

infrastructure/database.tf
Fix 
`Error modifying DB Instance scpca-portal-deployer-staging: InvalidParameterCombination: Cannot find upgrade path from 12.14 to 12.7` error
=> Update Postgres version from 12.7 to 12.14

client/src/pages/projects/[scpca_id].js
#426 
- prevents DOIs from rendering inline
- Bugfix (non-breaking change which fixes an issue)ting functionality to not work as expected)
n/a reloaded SCPCP00009 locally (has mutliple DOIs)
=> Wrap DOIs to force them newline

client/src/config/contribution-guidelines.md
#430 
- copy latest version of contributor guidelines (switches form links)
n/a
n/a
=> update to latest guidelines.md

client/package.json, client/src/pages/_app.js, client/yarn.lock
Closing #436
Resolved  the regenerator runtime error in the sample details tab. 
Please see the latest UI [here](https://scpca-portal-j4uk4b9hv-ccdl.vercel.app).
=> 436 - Resoive the regenerator runtime error in the sample details tab

client/src/theme/button.js
Closing #439
Fixed the button style overwritten issue.
@dvenprasad please review the latest UI [here](https://scpca-portal-qoo7454q8-ccdl.vercel.app).
=> 439 - Fix the button style overwritten issue

client/src/theme/global.js, client/src/theme/tabs.js
Closes #445
Based on the design update, changed the tab style on the project page.
@dvenprasad please review the latest UI [here](https://scpca-portal-e0tsmzxvv-ccdl.vercel.app).
=> 445 - Change tab style

client/src/components/DownloadStarted.js, client/src/components/ProjectHeader.js, client/src/components/WarningText.js
Correct link label typo. Test reviewers automatic assignment.
=> Correct link label typo

api/scpca_portal/views/stats.py
Resolves #450 
Update samples_count query to include distinct samples only.
=> Use distinct samples for samples stats endpoint

api/scpca_portal/models/computed_file.py, api/scpca_portal/models/project.py, api/scpca_portal/test/management/commands/test_load_data.py
https://github.com/AlexsLemonade/scpca-portal/issues/447
Refactor tests to use the new single project test data structure.
=> Adjust load data tests to a new test data structure

api/scpca_portal/test/management/commands/test_load_data.py
Use new variables syntax:
> For example, previously, we had been using <contact 1>;<contact 2> , but we are now using curly braces {contact 1};{contact2}. We are using <> around the URLs in the external accession instead.
=> Update tests: use new variables syntax

api/scpca_portal/models/project.py, api/scpca_portal/test/management/commands/test_load_data.py
Update external accessions handling:
- Skip meaningless values
- Strip "<>" from URLs
=> Update external accessions handling

api/scpca_portal/models/project.py, api/scpca_portal/test/management/commands/test_load_data.py
Update citations handling: strip "<>"
=> Update citations handling: strip "<>"

.pre-commit-config.yaml
Fix [WARNING] The 'exclude' field in hook 'trailing-whitespace' is a regex, not a glob -- matching '/*' probably isn't what you want here.
// The failing tests aren't related to the PR's changes.
=> Update trailing-whitespace exclude value

infrastructure/api.tf
The 2x volume size amout has been calculated based on ~230G SCPCP000003's (currently failing) size: `size_of(SCPCP000003) * 3`
=> Increase volume size from 350G to 700G

infrastructure/api.tf
=> Resize data volume from 700G to 800G

api/scpca_portal/models/project.py
#499 
Set Sample::has_cite_seq_data based on sample's metadata file only.
=> Fix Sample::has_cite_seq_data determination logic

infrastructure/api.tf
The volume size has been calculated based on ~390G SCPCP000008's (currently failing) size: size_of(SCPCP000008) * 3.5
=> Resize data volume from 800G to 1.4T

api/scpca_portal/models/computed_file.py, api/scpca_portal/models/project.py
#499 
Fix AnnData/CITE-seq samples.
=> Update AnnData/CITE-seq data processing

api/scpca_portal/serializers.py, api/scpca_portal/test/serializers/test_computed_file.py
Resolves #504
Update ComputedFile serializer, add tests.
=> Update `ComputedFile` serializer: add `format` field

api/README.md, api/scpca_portal/common.py, api/scpca_portal/config/common.py, api/scpca_portal/config/local.py, api/scpca_portal/management/commands/load_data.py, api/scpca_portal/models/computed_file.py, api/scpca_portal/models/project.py, api/scpca_portal/models/sample.py, api/scpca_portal/test/management/commands/test_load_data.py, bin/sportal, setup.cfg
https://github.com/AlexsLemonade/scpca-portal/issues/506
Optimize data loading process using thread pool executors. This PR also contains load data class structure changes as well as migration to `pathlib`.
=> Optimize data loading process

api/scpca_portal/common.py
Add missing path existence check
=> Add missing path existence check

api/README.md, api/scpca_portal/management/commands/load_data.py, docker-compose.yml
Resolves #509 
This PR adds ability to control AWS S3 related configuration flags.
=> Add AWS configuration flags

infrastructure/api.tf, infrastructure/tf_vars/dev.tfvars, infrastructure/tf_vars/prod.tfvars, infrastructure/tf_vars/staging.tfvars
Resolves #516 
- change volume type from `gp2` to `gp3`
- change instance type from `t2.small` to `t2.medium`
=> Scale up API instance

api/scpca_portal/test/models/test_computed_file.py
Add ComputedFile::create_download_url test
=> Add ComputedFile::create_download_url test

client/src/pages/index.js
Closing #502
I updated the portal description with a new tagline on the homepage:
`Growing database of uniformly processed single-cell data from pediatric cancer tumors and model systems.`
Please see the latest UI [here](https://scpca-portal-8wsoqgdnf-ccdl.vercel.app/).
=> 502 - Update Portal description on homepage

api/scpca_portal/models/project.py, api/scpca_portal/templates/readme/anndata.md, api/scpca_portal/templates/readme/multiplexed.md, api/scpca_portal/templates/readme/single_cell.md, api/scpca_portal/templates/readme/spatial.md
=> Use templates for README files generation

client/src/api/resources/computedFiles.js, client/src/components/Download.js, client/src/components/DownloadOption.js, client/src/components/DownloadOptions.js, client/src/components/DownloadStarted.js, client/src/components/ProjectHeader.js, client/src/components/ProjectSamplesTable.js, client/src/components/Table.js, client/src/config/downloadOptions.js, client/src/contexts/ScPCAPortalContext.js, client/src/pages/projects/[scpca_id].js
N/A rest of anndata integration changes
- remove reference to computedfile.type (being phased out)
- provide a new context for samples table (settings for samples wont interfere with project)
- add support for custom elements in table - to display download options
- add support for context, and new modal - use the new DownloadOptionsModal for samples
- update layout, use download context provider 
- add support for saved preferences
- update download options (configuration changes, removes computedfile.type references)
- clean up, add support for context
- support context, clean up old code
- update for helper changes
- clean up, add support for preselected file
n/a tested locally
=> ann data components

client/src/components/Download.js, client/src/components/DownloadOption.js, client/src/components/DownloadOptions.js, client/src/components/DownloadOptionsModal.js, client/src/components/DownloadStarted.js, client/src/components/HelpLink.js, client/src/components/ProjectHeader.js, client/src/components/ProjectSamplesTable.js, client/src/components/Table.js, client/src/config/downloadOptions.js, client/src/contexts/DownloadOptionsContext.js, client/src/contexts/ScPCAPortalContext.js, client/src/helpers/filterWhere.js, client/src/helpers/getDefaultComputedFile.js, client/src/helpers/getDownloadOptionDetails.js, client/src/helpers/getReadable.js, client/src/helpers/getReadableOptions.js, client/src/helpers/objectContains.js, client/src/helpers/pick.js, client/src/hooks/useDownloadOptionsContext.js, client/src/pages/projects/[scpca_id].js
N/A
No real changes here just ran eslint
n/a
n/a
=> ann data eslint

client/src/components/Layout.js
Closes #583
I've removed the annData banner related code blocks in `Layout`.
Please see the latest UI [here](https://scpca-portal-knlonijmj-ccdl.vercel.app/).
=> 583 - Take down AnnData loading banner

api/scpca_portal/migrations/0038_auto_20240320_2042.py
Reverts AlexsLemonade/scpca-portal#621
Commenting this out fixed the issue. So reverting this change before we deploy to production.
Tests should pass.
=> Revert "temp comment out sample.is_cell_line migration"

api/scpca_portal/management/commands/load_data.py
https://github.com/AlexsLemonade/ScPCA-admin/issues/834
Adds `wu` and `rokita` to whitelist for loading data.
n/a
n/a
=> Add wu and rokita to whitelist

client/src/components/MarkdownPage.js, client/src/config/terms-of-use.md, client/src/helpers/slugify.js, client/src/pages/terms-of-use.js
N/A
- Updates terms for community contribution release.
- This file was not edited directly but there are commit for other versions of the output from the odt -> md conversion. This will ensure consistency between version updates of the original document.
- Removes bullet points in the `pages/terms-of-use` for clarity.
N/A
=> terms update 2024 04 06

api/scpca_portal/views/computed_file.py
N/A
- Adds the `includes_merged` to the computed file detail serializer
N/A
N/A
=> add includes_merged to detail serializer

.github/PULL_REQUEST_TEMPLATE.md
N/A
Adding an option for `refactoring` as a `type of change`.
N/A
N/A
N/A
N/A
=> Add refactor as additional option for pr template

api/scpca_portal/templates/readme/anndata.md, api/scpca_portal/templates/readme/anndata_merged.md
#667 
- Updates any reference of hdf5 to h5ad in templates used for anndata readmes
N/A
N/A
=> hdf5 -> h5ad in readmes

client/src/components/ProjectSamplesTable.js
#660 
- fixes the rendering of est demux sample count
n/a checked locally
=> Fix for est demux cell count

client/src/pages/about/index.js
Closes https://github.com/AlexsLemonade/scpca-portal/issues/688
Fixing some minor copy issues on the About Page
=> About page copy fixes

client/src/components/Logo.js
N/A
Merging changes from `dev` into `feature/refactor-load-data` in advance of merge of feature branch into `dev`.
N/A
N/A
N/A
=> Merge updated changes from dev into refactor-load-data feature branch

api/scpca_portal/templates/readme/anndata_merged.md, api/scpca_portal/templates/readme/single_cell_merged.md
#722
- Correct use of double curly brace `{{ variable }}` in merged readmes
- adds space for better readability
n/a
N/A
=> 722 merged readme template variables

api/scpca_portal/models/contact.py, api/scpca_portal/models/external_accession.py, api/scpca_portal/models/publication.py
n/a
While processing data for staging, most projects went through successfully however there was an issue where we formatted data and put it in the DB after checking if the unformatted data was in the DB. Obviously this doesn't work so this PR  changes the order so that we check if the formatted values are in the DB.
- also updated models that do something similar to prevent future issues.
n/a
n/a
=> Fix issue with duplicate emails

client/src/components/ProjectSamplesTable.js
Closing #754
@dvenprasad, please see the latest UI [here](https://scpca-portal-fohd05uh6-ccdl.vercel.app/).
=> 754 - Samples table: Sort on Other modailities is not working

api/scpca_portal/management/commands/load_data.py
N/A
- Whitelists Collins for upcomming data release
N/A
N/A
=> Add collins to whitelist

client/src/components/ProjectSamplesTable.js
Closing #753
The following changes are included in this PR:
- Changed the name of the sample colum from "Other Modalities" to "Modalities"
- Prefixed the above column values with "Single-cell" and removed the default "NA" value
@dvenprasad Please see the latest UI [here](https://scpca-portal-fay0p0ep5-ccdl.vercel.app/).
N/A
N/A
=> 753 - Samples table: Change 'Other Modalities' to 'Modalities' 

api/scpca_portal/common.py, api/scpca_portal/management/commands/load_data.py, api/scpca_portal/metadata_file.py, api/scpca_portal/test/test_metadata_file.py, client/src/components/ProjectSamplesTable.js
N/A
Handled small merge conflict in `common.py`.
N/A
N/A 
N/A 
N/A
=> Handle merge conflicts on merge from dev into feature/remove-file-mappings

api/scpca_portal/common.py, api/scpca_portal/management/commands/load_data.py, api/scpca_portal/metadata_file.py, api/scpca_portal/test/test_metadata_file.py, client/src/components/ProjectSamplesTable.js
=> Merge dev updates into remove-file-mappings feature branch

api/scpca_portal/models/computed_file.py, api/scpca_portal/models/project.py, api/scpca_portal/readme_file.py
N/A
Readme creation updates includes:
- Addition of the `readme_file`module
- Adjustment in `ComputedFile` model
- Removal of obsolete code blocks
N/A
N/A
N/A
N/A
=> Merge dev updates into feature/portal-medatada-command

api/scpca_portal/common.py, api/scpca_portal/models/library.py, api/scpca_portal/models/project.py, api/scpca_portal/test/management/commands/test_load_data.py
The following issue introduced the update to the input bucket of nesting bulk files in their own directory: https://github.com/AlexsLemonade/ScPCA-admin/issues/904
- Make updates to `Project` and `Library` models to accommodate new `bulk` directory in testing bucket
- Update version of testing bucket to `2024-06-28`
N/A
N/A
=> Accommodate Handling of Bulk Nested Directory, Update Testing Bucket

api/scpca_portal/migrations/0047_library_project.py
N/A
Looks like our staging DB is in a intermediate state. One of the project's samples is not populated correctly. Since the migrations weren't applied exploring the DB via the ORM is a bit tricky. I am going to apply this change to see if it is more permissive and allows the migration to go through. This is a minimal change. Otherwise, I will wipe staging db, migrate, and rerun the load data command to repopulate it.
N/A
N/A
=> hotfix database migration 47

api/scpca_portal/management/commands/load_data.py
N/A
- Adds `soragni` to the whitelist ahead of releasing new samples on the portal
N/A
N/A
=> Add soragni to whitelist

.github/workflows/push.yml, bin/sportal, recreate_schema.sh, run_psql_client.sh
N/A
- Removes all references to `docker-compose` command in favor of current `docker compose`
n/a
n/a
=> docker-compose to docker compose

.github/workflows/push.yml, api/run_tests.sh, api/scpca_portal/management/commands/configure_aws_cli.py, api/scpca_portal/management/commands/load_data.py, api/scpca_portal/models/computed_file.py, api/scpca_portal/models/library.py, api/scpca_portal/models/project.py, api/scpca_portal/models/sample.py, api/scpca_portal/s3.py, api/scpca_portal/test/management/commands/test_load_data.py, api/scpca_portal/test/models/test_computed_file.py, api/scpca_portal/test/test_s3.py, api/scpca_portal/test/test_utils.py, api/scpca_portal/utils.py, bin/sportal, infrastructure/api-configuration/start_api_with_migrations.tpl.sh, recreate_schema.sh, run_psql_client.sh
https://github.com/AlexsLemonade/scpca-portal/issues/767
This PR introduces the following changes:
- Move all logic that handles `s3` to a new `s3` module
- Add generic `download_s3_files` function to `s3` module which downloads all files from an S3 bucket according to a list of passed filters
- Add following functions to `s3` module, all of which leverage `download_s3_files`:
-  `download_metadata_files` (called inside of `load_data` command)
- `download_data_files` (called inside of `ComputedFile::get_project_file` and `ComputedFile::get_sample_file`)
N/A
N/A
=> 767 - Just In Time Data File Downloads

infrastructure/variables.tf
N/A
Recently upgraded minor versions to 12.19. Our db went under some upgrades during the last maintenance window and in addition to the minor version, the instance type had also changed. This PR updates the instance type to match.
N/A
N/A
=> db.t2.micro -> db.t3.micro

infrastructure/database.tf
#848 
- Creates data variable populated with latest rds ca cert
- Enforces API DB instance to use that cert
N/A
N/A
=> 848 - Enforce latest RDS CA

api/scpca_portal/s3.py, api/scpca_portal/test/test_s3.py
https://github.com/AlexsLemonade/scpca-portal/issues/817
All test cases where updated in the `test/test_s3` module. See the breakdown below.
Tests added:
- `test_list_input_paths_correct_command_inputs`
- `test_list_input_paths_recursive_flag_passed_by_default`
- `test_list_input_paths_public_in_bucket_name`
Tested updated:
- `test_list_input_paths_command_success_recursive`
- `test_list_input_paths_command_success_non_recursive`
- `test_list_input_paths_command_failure`
Tests deleted:
- `test_list_input_paths_with_relative_path`
- `test_list_input_paths_with_nested_directory`
Tests listed above.
N/A
=> 817 - Update test_s3 module

api/scpca_portal/management/commands/load_data.py, api/scpca_portal/management/commands/load_metadata.py, api/scpca_portal/metadata_file.py, api/scpca_portal/models/project.py, api/scpca_portal/test/management/commands/test_load_metadata.py
https://github.com/AlexsLemonade/scpca-portal/issues/840
Added `load_metadata` command which takes the `load_data` command and removes all computed file generation functionality.
Added `test_load_metadata` test module which takes the test cases from `test_load_data` and removes all testing related to computed file generation.
Added `test_load_metadata` test module.
N/A
=> 840 - Add load metadata command

api/scpca_portal/loader.py, api/scpca_portal/management/commands/generate_computed_files.py, api/scpca_portal/management/commands/load_data.py, api/scpca_portal/management/commands/load_metadata.py, api/scpca_portal/test/management/commands/test_load_data.py, api/scpca_portal/test/management/commands/test_load_metadata.py
https://github.com/AlexsLemonade/scpca-portal/issues/863
Created a new `loader` module, which houses common logic from the `load_data`, `load_metadata` and `generate_computed_files` commands.
A variety of top levels functions were added in the `loader` module to be called by the commands to better consolidate and self-document logic within the flow of execution. As well, some methods previously used in some of these commands have been designated as private methods for internal use.
Will be handled in https://github.com/AlexsLemonade/scpca-portal/issues/864
N/A
=> 863 - Add Loader Module

infrastructure/batch/compute_environment.tf, infrastructure/batch/roles.tf, infrastructure/batch/security.tf
*Note  - The base for this PR will be updated to `feature/batch` once `avrohom/clean-up-load-data` is merged into `feature/loader`, and `feature/loader` is merged into `feature/batch`
https://github.com/AlexsLemonade/scpca-portal/issues/844
Describe the big picture of your changes.
Additions in this PR
- `batch/` directory inside of `infrastructure/`
- `batch/compute_environment.tf` file which describes the compute environment
- `batch/roles.tf` which details necessary roles and their role policies for the compute environment
- `batch/security.tf`  which details the necessary security group for the compute environment
N/A
=> 844 - Add Batch Compute Environment

infrastructure/batch/compute_environment.tf, infrastructure/batch/job_queue.tf, infrastructure/batch/roles.tf, infrastructure/batch/security.tf
Closes https://github.com/AlexsLemonade/scpca-portal/issues/900
This PR introduces the `aws_batch_job_queue` resource.
N/A
N/A
=> 900 - Add Batch Job Queue

api/scpca_portal/config/test.py, api/scpca_portal/test/test_readme_file.py
N/A
Fixes an issue with the latest addition of test settings in the test_readme_file test.
N/A ran the tests
N/A
=> add README_RENDERED_PATH to test settings

infrastructure/batch/job_definition.tf, infrastructure/batch/job_queue.tf
Closes https://github.com/AlexsLemonade/scpca-portal/issues/901
This PR introduces the `aws_batch_job_definition` resource.
N/A
N/A
=> 901 - Add Batch Job Definition

client/src/components/ProjectSamplesTable.js, client/src/components/Table.js
Closes #917
Fixed filtering bugs in the following components:
- `Table`
- `ProjectSamplesTable`
N/A
N/A
=> 917 - Fix filtering in the project samples table

api/scpca_portal/test/management/commands/test_create_portal_metadata.py
Closes #916
I've cleaned up `assertProjectReadmeContent` and replaced the hard-coded download config value with `common.GENERATED_PORTAL_METADATA_DOWNLOAD_CONFIG`.
N/A
N/A
=> 916 - Clean up the portal management command test

api/scpca_portal/common.py
N/A
Adds `pushel` to submitter whitelist so we can load their projects into the portal.
N/A
N/A
=> Add pushel to whitelist

.gitignore, infrastructure/README.md, infrastructure/api-configuration/run_command.tpl.sh, infrastructure/api-configuration/start_api_with_migrations.tpl.sh, infrastructure/api.tf, infrastructure/batch/job_definition.tf, infrastructure/deploy.py, infrastructure/variables.tf
Closes https://github.com/AlexsLemonade/scpca-portal/issues/939
This PR makes slight corrections to the deploy script and infrastructure readme in order to enable the spinning up of a dev stack.
N/A
N/A
=> 939 - Update deploy script and infrastructure readme

infrastructure/api.tf, infrastructure/batch.tf, infrastructure/provider.tf
N/A
- Disables batch to allow for upgrade path to 5.x via 4.x from 3.x
N/A
N/A
=> Upgrade aws provider version to 4.0.0

infrastructure/provider.tf
Before upgrading to aws provider version 4.0.0 (on our way to 5.12.0), we're going to upgrade to the last 3.x version (which is 3.76.1)
N/A
N/A
=> Downgrade aws provider version from 4.0.0 to 3.76.1

infrastructure/init_terraform.py
In order to get more information, we've set `TF_LOG=trace` in the init_terraform script.
N/A
N/A
=> Set TF_LOG to trace in init_terraform script

infrastructure/init_terraform.py
This should add logging to debug the terraform issue.
N/A
N/A
=> Update popen command with TF_LOG envar

infrastructure/init_terraform.py
Describe the big picture of your changes.
=> remove unnecessary double TF_LOG

infrastructure/init_terraform.py, infrastructure/provider.tf
Removing upgrade, adding in required providers block. Changing source to `-/aws` from `hashicorp/aws`.
N/A
N/A
N/A
=> Try different source and newer requirement version locking

infrastructure/database.tf
In https://github.com/AlexsLemonade/scpca-portal/pull/978 we removed all duplicate tags. The one was left. The Batch ones were not addressed here.
=> Remove extra db tag

infrastructure/api.tf, infrastructure/database.tf, infrastructure/provider.tf, infrastructure/s3.tf, infrastructure/variables.tf
Upgrade aws provider version from 4.x to 5.x.
We also handled the following deprecation warnings
- Change `name` field on db instance to `db_name`
- Updated private acl handling in `s3`
N/A
N/A
N/A
=> Upgrade aws provider to version 5.x

.github/workflows/deploy_prod_backend.yml, .github/workflows/deploy_staging_backend.yml, infrastructure/provider.tf
Describe the big picture of your changes.
=> Downgrade terraform version to 0.14

.github/workflows/deploy_prod_backend.yml, .github/workflows/deploy_staging_backend.yml, infrastructure/provider.tf
There was a problem with 0.14.8, so we're downgrading to 0.14.0.
See logs for more details
https://github.com/AlexsLemonade/scpca-portal/actions/runs/11979134928/job/33400657705
N/A
N/A
N/A
=> Downgrade from terraform version to 0.14.0

.github/workflows/deploy_prod_backend.yml, .github/workflows/deploy_staging_backend.yml, infrastructure/provider.tf
As per the failing of downgrading from 1.0 to 0.14, we're now going to try from 0.13 and upwards.
Here is the previous GHA which failed: https://github.com/AlexsLemonade/scpca-portal/actions/runs/11979228111/job/33400945129
=> Downgrade to terraform version 0.13.0

infrastructure/deploy.py, infrastructure/replace_provider.py
=> Add replace_provider command

infrastructure/deploy.py
N/A
- lock was successfully removed
- removing calling the unlock function so we can test later in the deploy process
- N/A
N/A
=> remove calling unlock in deploy

infrastructure/deploy.py
N/A
- In deploy script when reading outputs for taint and apply. This PR changes how we parse the output before loading json into a dict.
N/A
N/A
=> decode stdout

infrastructure/deploy.py
N/A
Does what it says on the tin. Apparently, the json structure doesnt match the terraform structure. This will help us see why.
N/A
N/A
=> dump outputs after run_terraform

infrastructure/deploy.py
N/A
- Outputs are now nested so we need to grab the value instead of the whole object.
N/A
N/A
=> handle nested value in terraform output -json

infrastructure/provider.tf
N/A
Does what it says on the tin.
N/A
N/A
=> upgrade terraform aws provider to 5.x

infrastructure/provider.tf
N/A
- same thing as before but now with more commas
N/A
N/A
=> fix syntax error

infrastructure/api-configuration/environment.tpl, infrastructure/api.tf, infrastructure/batch.tf, infrastructure/networking.tf
N/A
- Enables batch for testing
- fixes deprecation warning around vpc needing to be a domain attribute
N/A
N/A
=> Enable batch

infrastructure/api-configuration/environment.tpl
When Batch was re-enabled on staging, the job_queue and job_definition envars were missed in `infrastructure/environment.tpl`. This PR re-adds them.
N/A
N/A
N/A
=> Fix batch envars error

infrastructure/unlock_state.py
N/A
The `infrastructure/unlock_state` script was templated from the `replace_provider` script, but the docstring wasn't updated. This PR updates the `unlock_state` docstring.
N/A
N/A
N/A
=> Update docstring in unlock_state script

infrastructure/batch.tf, infrastructure/batch/compute_environment.tf, infrastructure/batch/job_definition.tf, infrastructure/batch/job_queue.tf, infrastructure/batch/roles.tf, infrastructure/batch/security.tf, infrastructure/batch/variables.tf
Closes https://github.com/AlexsLemonade/scpca-portal/issues/960
Tags were added to all Batch resources so that we'll be able to gain better insight into usage during cost analysis.
N/A
N/A
N/A
=> 960 - Add Tags to Batch Resources

infrastructure/ses.tf, infrastructure/variables.tf
https://github.com/AlexsLemonade/scpca-portal/issues/1037
- Add domain and dkim resources needed to send `ses` test emails
N/A
N/A
=> 1037 - Ses domain verification

.github/ISSUE_TEMPLATE.md
N/A
It looks like Github dropped support for the old style of Issue templating and now requires a header section in order for templates to be picked up.
We should discuss whether or not we want to keep the one general issue or if we'd prefer to break it up into different templates like other repos do.
N/A
N/A
N/A
=> Temporary Patch for Issue Templating

api/scpca_portal/management/commands/dispatch_to_batch.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1062
The `--regenerate-all` flag was not behaving properly as it wasn't correctly parsing the passed boolean value. Adding an `OptionalBooleanAction` action seems to have done the trick.
N/A
N/A
=> 1062 - Fix dispatch_to_batch regenerate-all flag bug

infrastructure/database.tf
#1071 
- Adds new parameter group for postgres 16
- upgrades postgres to 16.6 with new parameter group
N/A
N/A
=> 1071 - postgres upgrade to 16.xx

infrastructure/database.tf
#1071
- Fixes issue with naming collision on parameter group
n/a
N/A
=> unique name for parameter group

api/scpca_portal/management/commands/dispatch_send_test_email.py, api/scpca_portal/management/commands/send_test_email.py
Fix parser add_argument typos in send_test_email and dispatch_send_test_email management commands.
N/A
N/A
=> Fix parser add_argument typos

infrastructure/api-configuration/environment.tpl
Add missing dollar sign to aws_ses_domain envar.
N/A
N/A
=> Fix envars bug (missing dollar sign)

api/scpca_portal/management/commands/dispatch_send_test_email.py
Fix command semantics.
N/A
N/A
=> Fix command semantics

infrastructure/batch/roles.tf
Add `aws_iam_role_policy_attachment` to attach `batch_ses_send_email` policy to `batch_job_role`.
N/A
N/A
=> Attach ses send policy to batch job role

api/README.md
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1098
This PR updates the Cloud Data Management section of the API readme, taking recent changes into account. 
Among recent changes includes:
- The addition of the Batch workflow and the `dispatch_to_batch` command
- The more granular approach of loading data on the API via the `load_metadata` and `generate_computed_files` commands
N/A
N/A
=> 1098 - Update cloud data management in API readme

.github/workflows/deploy_prod_backend.yml, .github/workflows/deploy_staging_backend.yml, api/scpca_portal/config/common.py, infrastructure/api-configuration/environment.tpl, infrastructure/api.tf, infrastructure/deploy.py, infrastructure/variables.tf
https://github.com/AlexsLemonade/scpca-portal/issues/1104
This PR makes the `SLACK_CCDL_TEST_CHANNEL_EMAIL` envar available as the `TEST_EMAIL_RECIPIENT` on the API. This after we cycled it in slack and made it available in 1password and GHA.
N/A
N/A
=> 1104 - Cycle test email address

api/scpca_portal/enums/__init__.py, api/scpca_portal/enums/dataset_formats.py, api/scpca_portal/models/dataset.py
Closes #1116 
I've added the `DatasetFormats` class in the `enum` folder for the `format` field of the `Dataset` model.
N/A
N/A
=> 1116 - Use DatasetFormats enum for Dataset's file formats

api/scpca_portal/test/factories.py, api/scpca_portal/test/models/test_dataset.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1114
This PR introduces the test_dataset testing module. A simple test is created which asserts that a dataset factory instance is instantiated and saved correctly to the db.
- TestDataset::test_dataset_saved_to_db
N/A
=> 1114 - Dataset factory test

api/README.md, infrastructure/README.md
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1102
This PR updates the Local Data Management section of the API Readme in light of all of the recent changes to the API. The main changes include 
- Adding a description of the OriginalFile model and the sync_original_files command
- Removing references to load_data flags which have since been removed
- Adding a description of the load_metadata and generate_computed_files commands
N/A
N/A
=> 1102 - Update local data management section of API readme

client/package.json, client/vercel.json
N/A
Revert the Vercel deploy for Storybook.
N/A
N/A
=> Revert Vercel Storybook deploy scripts

client/.storybook/stories/DatasetMoveSamplesModal.stories.js, client/package.json, client/src/components/DatasetMoveSamplesModal.js, client/src/components/InfoText.js, client/src/components/WarningText.js, client/src/config/index.js, client/vercel.json
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1144.
This PR introduces the `DatasetMoveSamplesModal` component, which allows users to move samples to their cart from previously generated datasets.
N/A
N/A
=> 1144 - Add Move Samples Modal

api/scpca_portal/batch.py, api/scpca_portal/models/job.py, api/scpca_portal/test/models/test_job.py
N/A
This is a prerequisite PR for #1146
- Added the `scpca_portal/batch.py` module to decouple the `boto3` and `logger` dependencies from the `Job` model
- Integrated the `batch` module into the `Job` model
- Updated `TestJob` to reflect the changes
N/A
N/A
=> 1146 - Add batch.py module for the Job model

client/.storybook/stories/DatasetSummaryTable.stories.js, client/src/components/DatasetSummaryTable.js
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1162.
This PR adds the Dataset Summary Table for the Cart UI.
N/A
N/A
=> Add Dataset Summary Table

client/.storybook/stories/MyDatasetButton.stories.js, client/src/components/MyDatasetButton.js, client/src/theme/text.js
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1161.
This PR adds the MyDataset button for the Cart UI.
N/A
N/A
=> Add MyDataset Button

client/.storybook/stories/DatasetChangingMergedProjectModal.stories.js, client/src/components/DatasetChangingMergedProjectModal.js, client/src/config/index.js
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1176.
This PR adds the ChangingMergedProjectModal component.
N/A
N/A
=> 1176 - Add ChangingMergedProjectModal Component

api/scpca_portal/ccdl_datasets.py, api/scpca_portal/models/dataset.py, api/scpca_portal/test/expected_values/dataset_all_metadata.py, api/scpca_portal/test/expected_values/dataset_all_metadata_SCPCP999990.py, api/scpca_portal/test/expected_values/dataset_single_cell_ann_data.py, api/scpca_portal/test/expected_values/dataset_single_cell_ann_data_SCPCP999990.py, api/scpca_portal/test/expected_values/dataset_single_cell_ann_data_merged.py, api/scpca_portal/test/expected_values/dataset_single_cell_ann_data_merged_SCPCP999990.py, api/scpca_portal/test/expected_values/dataset_single_cell_single_cell_experiment.py, api/scpca_portal/test/expected_values/dataset_single_cell_single_cell_experiment_SCPCP999990.py, api/scpca_portal/test/expected_values/dataset_single_cell_single_cell_experiment_merged.py, api/scpca_portal/test/expected_values/dataset_single_cell_single_cell_experiment_merged_SCPCP999990.py, api/scpca_portal/test/expected_values/dataset_single_cell_single_cell_experiment_no_multiplexed_SCPCP999991.py, api/scpca_portal/test/expected_values/dataset_spatial_single_cell_experiment.py, api/scpca_portal/test/expected_values/dataset_spatial_single_cell_experiment_SCPCP999990.py, api/scpca_portal/test/factories.py, api/scpca_portal/test/models/test_dataset.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1174.
This PR converts references to `.name` (which were incorrect) to `.value`.
N/A
N/A
=> 1174 - Convert .name to .value

.github/workflows/push.yml, .pre-commit-config.yaml, api/scpca_portal/config/logging.py, api/scpca_portal/wsgi.py
Closes #1186 
- upgrades pre-commit action to 3.0.1
- updates hooks
N/A
N/A
=> upgrade pre-commit action

.github/workflows/deploy_prod_backend.yml, .github/workflows/deploy_staging_backend.yml
N/A
- Adds -a for dockerhub account to github action with dockerhub account for staging
- updates prod as well
N/A
N/A
=> add -a dockerhub account

api/scpca_portal/serializers.py, api/scpca_portal/test/views/test_dataset.py, api/scpca_portal/views/dataset.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1218.
This PR adds the ability to send `post` requests to the `/datasets/` endpoint.
- `views::test_dataset::test_put`
N/A
=> 1218 - Add Dataset ViewSet Create Action

.github/workflows/deploy_prod_backend.yml
N/A
- Destroys Production Infrastructure
- Stands up Production Infrastructure with project account credentials
Production DB snapshot has been generated, shared, and is ready for use in project account.
Recent dev stack test.
N/A
=> Migrate prod to project account

.github/workflows/deploy_prod_backend.yml, .github/workflows/deploy_staging_backend.yml
N/A
- Removes old legacy destroy step from prod deploy
- Replaces new credentials
N/A 
N/A
=> remove legacy credentials and remove destroy

client/src/components/Table.js
Closes #1249 
I've fixed the misalignment in the `Multiplexed with` column of the project samples table, and resolved a `TypeError` in the `Table` component. 
Please see the latest UI [here](https://scpca-portal-aamknmv3u-ccdl.vercel.app/projects/SCPCP000009).
N/A
N/A
=> 1249 - Fix misalignment in Multiplexed with column and TypeError in Table

api/scpca_portal/serializers/dataset.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1237.
This PR consolidates `serializers/dataset.py` by creating inheritance relationships between the different custom serializers.
N/A
N/A
=> 1237 - Consolidate Dataset Serializers

api/scpca_portal/serializers/__init__.py, api/scpca_portal/serializers/project.py, api/scpca_portal/test/views/test_project.py, api/scpca_portal/views/project.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1233.
This PR adds a `datasets` field to the `ProjectLeafSerializer`, allowing for project instances to carry references to their associated ccdl datasets on the `projects-detail` and `projects-list` endpoints.
- `test/views/test_project::ProjectsTestCase::test_datasets_field`
N/A
=> 1233 - Add dataset project relationship

api/scpca_portal/common.py, api/scpca_portal/loader.py, api/scpca_portal/management/commands/generate_computed_file.py, api/scpca_portal/management/commands/generate_computed_files.py, api/scpca_portal/management/commands/load_data.py, api/scpca_portal/management/commands/load_metadata.py, api/scpca_portal/management/commands/process_dataset.py, api/scpca_portal/test/management/commands/test_load_data.py, api/scpca_portal/test/management/commands/test_load_metadata.py, api/scpca_portal/test/models/test_computed_file.py, api/scpca_portal/test/test_loader.py, api/scpca_portal/utils/helpers.py
Closes #1320
I've broken up the loader module into appropriate files and updated the corresponding tests to reflect these changes.
- Updated all references in the corresponding tests to reflect the changes
N/A
=> 1320 - Move the loader methods to the appropriate files

client/src/api/resources/datasets.js
Closes #1325
Feature branch: `feature/dataset-integration`
I've added the `datasets` resource to `api/resources` to support the `datasets` endpoint.
N/A
N/A
=> 1325 - Add the datasets resource to the api/resources folder folder

client/src/api/index.js, client/src/api/resources/ccdlDatasets.js, client/src/api/resources/datasets.js, client/src/contexts/CCDLDatasetContext.js, client/src/hooks/useCCDLDataset.js
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1383.
- Add useCCDLDataset hook
- Add ccdlDataset route
- Update dataset route
N/A
N/A
=> 1383 - Add useCCDLDataset hook

client/src/components/DatasetPortalWideDownloadCard.js, client/src/components/Layout.js, client/src/pages/portal-wide.js
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1387.
- Adds static elements to portal-wide downloads page, including
- header section
- metadata downloads section
- data downloads section
N/A
N/A
=> 1387 - Build Out Portal Wide Page Structure

client/src/components/Header.js, client/src/components/MyDatasetButton.js
Closes #1378 
- Include a link to `/download` in ` MyDatasetButton`
-  Add `MyDatasetButton` to `Header`
- Clicking `MyDatasetButton` in the global navigation directs to `/download`
N/A
=> Add the MyDatasetButton component to Header

api/scpca_portal/management/commands/create_ccdl_datasets.py, api/scpca_portal/models/dataset.py, api/scpca_portal/test/management/commands/test_create_ccdl_datasets.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1359.
- Consolidate logic from `attempt_dataset` method into main `create_ccdl_datasets` method
- Fix bug with `ignore-hash` flag not being picked up, and add test
- test_create_ccdl_datasets::test_ignore_hash
N/A
=> Refactor ccdl datasets command

api/scpca_portal/management/commands/create_ccdl_datasets.py, api/scpca_portal/models/dataset.py, api/scpca_portal/models/job.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1358.
- Regroup `Dataset` model methods
- Regroup `Job` model methods
N/A
N/A
=> Regroup Dataset and Job Model Methods

.github/workflows/deploy_prod_backend.yml
N/A
Fixes an issue with ENABLE_FEATURE_PREVIEW not defined for prod deploy
N/A
N/A
=> Deploy hotfix no default for enable feature preview

api/scpca_portal/batch.py, api/scpca_portal/exceptions.py, api/scpca_portal/models/job.py, api/scpca_portal/test/models/test_job.py
Closes #1426
- Changed log level from `INFO` to `DEBUG` in the `batch` module
- Removed the custom exception `BatchGetJobsFailedError` from `exceptions`
- Updated `Job.sync_state `and `Job.bulk_sync_state`, along with the corresponding test, to reflect the changes above
N/A
=> Update modules level logs to be DEBUG log level
