AlexsLemonade/scpca-portal

- client/pages/_document.js
#7
* adds the `_document.js` page to insert google analytics and hotjar
* adds the `styled-components` readable name parts because it was a good time to do it
n/a
n/a
> 7 adds google analytics

- api/scpca_portal/urls.py
#18 
This gives us 3 HTML interfaces for the API. Probably too many. I've attached screenshots of them all. I'd appreciate some opinions about what interface should be exposed via what route.
I've run things locally to create the following screenshots.
As this PR stands, the following URLs will show the following pages:
http://0.0.0.0:8000/v1/
http://0.0.0.0:8000/v1/redoc/
http://0.0.0.0:8000/v1/swagger/
> Add urls and config for API docs.

- api/scpca_portal/management/commands/load_data.py
- api/scpca_portal/models/computed_file.py
- api/scpca_portal/test/factories.py
N/A Things broke when the input format changed
These used to have this in them, now they don't.
I also was getting `null value in column "s3_bucket" violates not-null constraint` errors when trying to purge a project because we were setting `s3_bucket` and `s3_key` to null when we deleted them from s3. I'd rather have the not null constraint than be able to set them to None right before we delete them though.
I've run
```
sportal manage-api load_data --reload-existing --upload True
```
To update the local data bucket.
> Remove trailing _sce postfix from file names.

- api/scpca_portal/test/views/test_computed_file.py
- bin/sportal
#55 
#55 should have failed, but it didn't because the exit code of `sportal` wasn't correct. This should prevent that from happening in the future.
I've made sure `sportal test-api` with a failing test has an exit code of 1.
> Make sure the exit code of sportal matches the command it calls.

- api/scpca_portal/config/common.py
- api/scpca_portal/test/views/test_computed_file.py
N/A just came up for @davidsmejia 
Adds the API-KEY header to CORS to allow API tokens to be accepted.
mmmm @davidsmejia how do I test this?
> Add API-KEY to allowed CORS headers.

- api/scpca_portal/test/views/test_computed_file.py
- api/scpca_portal/views/computed_file.py
N/A @davidsmejia thought something broke but it was just a bad token
Silent failures bad! If there's a token and it's not valid, return a 403.
I've added a unit test.
> Bad tokens cause a 403 rather than just not providing a download URL.

- api/scpca_portal/models/sample.py
#87 
I also had this in another branch. I just didn't save the project summary when it exists and needs to be incremented.
I've tested this in the new import branch.
> Actually save project_summaries as we update them

- .github/workflows/deploy_prod_backend.yml
https://github.com/AlexsLemonade/scpca-portal/issues/16
This should get prod deploying on pushes to master. Once we run a deploy I can use the EIP address created to setup the DNS for the prod API.
Can't really until we merge to master.
> Add github actions workflow for prod deploy.

- api/Dockerfile.local
- api/scpca_portal/management/commands/load_data.py
- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
- infrastructure/api-configuration/load_data.tpl.sh
- infrastructure/api.tf
#102 
We don't have a `/home/user/code` directory in the prod image, that's just for development code. This fixes the default paths for production.
I'm testing this with a dev stack.
> Fix data paths for production docker images

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
- infrastructure/api.tf
- infrastructure/permissions.tf
- infrastructure/s3.tf
I think there is one somewhere but I can't find it.
This will store our SSL certs into S3 when they're created with an expiration of 30 days. If they haven't expired yet, then they'll be used instead of making new ones.
This way we won't hit certbot limits.
I've tested these things as best as I can by looking at the prod API instance and testing on a dev one, but I can't test it for real until at least staging.
This is from a test object I uploaded to the bucket
> Save ssl certs between deploys

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
#109 
It failed because it didn't have `zip`!
> Install zip command on API server

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
#109 
The certs were installed but nginx wasn't using them! This fixes that.
I made these changes to staging manually and it worked!
> Fix the nginx config when reusing certbot certs.

- api/scpca_portal/config/readme_template.md
Closes #144 
Here I'm adding the description of the files that are included in a download if a project has bulk RNA-seq. I just took the sentences that describe what the files are from the download files section of the docs, since here we are only describing the contents of the download. I didn't think there was anything else to expand on other than listing the two files, what they contain, and then we have the link to the download section of the docs. 
I also removed the `metadata.json` from the list of files included in the single cell download since we do not include that file anymore and updated the name for the `single_cell_metadata.tsv` file.
> Add description of bulk files to README template

- infrastructure/database.tf
#138 
Adds a new parameter group because the lifecycle create_before_destroy does not seem to create before destroying.
n/a
n/a
> add new parameter group

- infrastructure/database.tf
#138 
Temporarily sets `allow_major_upgrade_version` to `true` also adds `apply_immediately` which will cause some downtime.
n/a
n/a
> allow major version upgrade

- client/src/components/ProjectSamplesTable.js
Related issue: #163 
* sample table: default sort order by (is downloadable / has computed_file)
* samples table: no download icon -> “Not Available \n For Download”
N/A
- [ x] Lint and unit tests pass locally with my changes
> add download initial sorting fuctionality

- client/src/components/ProjectSamplesTable.js
N/A
* Adds a check to only sort initial downloads when there are more samples than downloadable samples
N/A
n/a
> sort samples if not all downloadable

- api/scpca_portal/config/spatial_readme_template.md
Closes #204 
Here I have added in a new template readme that will specifically be for spatial downloads. I named the file `spatial_readme_template.md` and stored it in the same folder as the original `readme_template.md`. 
For the most part I took what was in the original readme and copied that over, keeping the same introduction, contact, citing, and terms of use. The main difference between the spatial readme and the readme used for all other downloads is the contents section which now includes the contents of a spatial folder, rather than the single-cell gene expression contents. Here I mostly took what we have in the [spatial docs](https://github.com/AlexsLemonade/scpca-docs/blob/main/docs/download_files.md#spatial-transcriptomics-libraries), listing the contents of the spatial folder …
> Add spatial readme template

- client/src/pages/_document.js
#178 
* Replaced the native HTML element <script> tags with Next.js built-in <Script /> Component(for ga/hotjar).
- [x ] Lint and unit tests pass locally with my changes
> 178 replace script tags with Script Wrapper Component

- api/scpca_portal/config/common.py
N/A
The staging API wasn't able to load the python application via uwsgi. I went on to the server and while poking around stopped and restarted the container. Starting the container sent some error logs where I saw the out of index error. I don't think this would occur locally because of how we initialize the application (with arguments).
n/a
n/a
> Staging API possible fix - out of index arguments list

- api/scpca_portal/models/project.py
- api/scpca_portal/models/sample.py
- api/scpca_portal/test/management/commands/test_load_data.py
- api/scpca_portal/test/views/test_filter_options.py
- api/scpca_portal/test/views/test_project.py
#219 
The counts mismatch is caused by the order of computed file instance / sample instance are creation (update counts is tied to sample creation). In order to fix this the project counts update process should be invoked after the computed file is created. 
Moreover, I don't see any reason why we need to update project counts every time we import a sample. It seems sufficient to run it once after the entire project is imported.
> Update project counts after samples import.

- api/README.md
- api/scpca_portal/management/commands/load_data.py
Add a flag to skip input bucket data sync when it's not needed.
> Add `skip-input-bucket-sync` flag.

- api/scpca_portal/models/project.py
- api/scpca_portal/models/sample.py
- api/scpca_portal/test/management/commands/test_load_data.py
#229 
Set `has_cite_seq_data`, `has_spatial_data` for samples in order to get project counts populated propertly.
Bugfix (non-breaking change which fixes an issue)
> Populate project-options modalities.

- client/.storybook/main.js
- client/package.json
- client/yarn.lock
N/A
Storybook wasn't able to build due to the latest upgrade to the environment plugin changing.
* adds dotenv-webpack to dev requirements
* fixes how env vars are assigned to the env
loaded up storybook locally
n/a
> Fix Storybook after upgrading deps

- api/scpca_portal/templates/readme_spatial.md
Closes #208 
When creating the spatial readme template, the docs weren't building properly so we had put a link to the download section, but could not include a link directly to the section that describes the spatial downloads.
Here, I updated the link to go specifically to the spatial section of the download rather than the top of the download files page. 
> Update link in spatial readme to link directly to spatial download section

- api/Dockerfile.local
Make ScPCA portal unit test running successfully.
The
`test_load_data_from_s3 (scpca_portal.test.management.commands.test_load_data.TestLoadData) ... qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
ERROR`
was causing 
`subprocess.CalledProcessError: Command '['aws', 's3', 'sync', '--delete', 's3://scpca-portal-public-test-inputs', '/home/user/code/test_data/input', '--no-sign-request']' returned non-zero exit status 255.`
error on ARM machine.
> Fix Apple M1 Docker image build error.

- infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
- infrastructure/api-configuration/nginx_config.conf
- infrastructure/api-configuration/start_api_with_migrations.tpl.sh
Summary of significant changes:
- Move Django static volume to `/var/www`.
- Reformat Nginx config files (auto).
- Remove unused includes from Nginx config.
- Remove unused options from API migration container run command. 
- Add `--platform` and `--restart` options to API docker container run command.
Fix the Nginx log writing permission denied issue.
Tested using dev deploy.
> Move Nginx logs to `/var/log/nginx` to avoid permission denied error.

- api/scpca_portal/templates/readme.md
- api/scpca_portal/templates/readme_multiplexed.md
Closes #326 
Here I just added the `_processed.rds` file to the list of files that are included in the download for both the main readme and the multiplexed readme. I didn't expand too much since we direct users to the docs.
> Include `_processed.rds` in template README files

- client/src/components/ProjectPublicationsDetails.js
- client/src/components/ProjectSearchResult.js
- client/src/helpers/getReadable.js
- client/src/pages/projects/[scpca_id].js
#339 
> We will be adding new relationships to the Project model: Publications and Contacts and we want to show them on the Project page.
- Included the publications and supported multiple contacts in the project detail tab 
- Included the publications in the project search result card
**NOTE:** Please reference the **SCPCP000005**, thank you!
The following updates were made based on the talk;
(in the project detail tab)
- "Publications"(plural)" section with its citation text and hyperlinked DOI string
- "DOI" section with the hyperlinked DOI url(is the same link location as above hyperlinked DOI string)
(in the search result card) …
> 339 - Update Frontend to support Publications + Contacts

- infrastructure/api.tf
N/A
SCPCP000008 has at least 80gb of files that get processed, we had ~250 gigs of space when I tried to import the project last. I keep encountering no disk space available when trying to import them. I would assume that we would need ~3x storage capacity for this. (1x for originals : 1x for zip per sample : 1x for project zip).
This PR bumps the volume up to 300gb which after processing I will scale back down to ~100.
n/a
n/a
> Temp change to bump up available storage

- .github/workflows/deploy_prod_backend.yml
- .github/workflows/deploy_staging_backend.yml
n/a
- forgot to prefix OP when adding sentry_dsn to 1password secrets.this fixes that
n/a
n/a
> add OP prefix to SENTRY_DSN

- client/src/components/ProjectPublicationsDetail.js
#383
> Both Publications and DOI can be displayed on separate lines.
Based on the above requirement, formatted the publications section. Please review the UI [here](https://scpca-portal-d0skj99qd-ccdl.vercel.app/projects?diagnoses=Retinoblastoma).
> 383 - Multiple publications are concatenated on the frontend

- client/src/components/Download.js
n/a
- when trying to download, this will try to get a new token if the current one doesn't work
- recreated token locally when the [`403`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) error occurs on the client-side.
n/a
> Refresh the user token if expired

- client/src/components/ProjectHeader.js
Closes #444
Based on the design update, increased the project title font size to 21px in the project card header.
@dvenprasad please review the latest UI [here](https://scpca-portal-git-nozomione-444-increase-project-tit-d5efbf-ccdl.vercel.app/projects).
> 444- Increase Project title font size to 21px

- api/scpca_portal/templates/readme.md
- api/scpca_portal/templates/readme_anndata.md
Closes #456 
This PR adds in a new template readme for AnnData downloads, `readme_anndata.md`. 
Mostly I mirrored the content of what's already included in the main `readme.md` for single-cell downloads. 
The only major modifications I made was including a description of the CITE-seq files since those are separate files for AnnData, but not for SCE objects. 
I also included the FAQ on working with the files in Python. Right now, that link won't work because the changes are in `development`. But it will work once those changes get merged in. 
And then the last thing I did was add in a link for the getting started docs. 
> Add readme for AnnData downloads

- api/README.md
- api/scpca_portal/management/commands/load_data.py
This PR adds a new flag `--cleanup-input-data` to the load data script in order to maintain its usability in tight available disk space constraints. The README file has been updated with an example of code for project processing with a minimum disk space footprint.
> Add load data script input data clean up flag

- api/scpca_portal/test/test_utils.py
- api/scpca_portal/utils.py
Update utils::get_today_string format -- replace minute (M) with mont (m)
> Update utils::get_today_string format

- client/src/config/index.js
#468 
We are now tagging release of scpca-docs.
- Nested links to stable from latest i.e. `/en/latest/download_files.html` to `/en/stable/download_files.html`
- When linking to the docs homepage we allow RTD to automatically redirect to the latest tag
- this will take effect after the next release it cut (after deploy)
n/a
n/a
> 468 - Docs to stable or root path

- client/src/components/ProjectExternalAccessionsDetail.js
- client/src/components/ProjectPublicationsDetail.js
- client/src/components/ProjectSearchResult.js
- client/src/pages/projects/[scpca_id].js
- client/src/theme/table.js
#455 
Adds support for displaying external accessions with the other project details.
We support two flavors of external accessions; comma separated list for search results, and one per line for project detail page.
Additionally adds a default array for publications for consistency and aligns table keys with values at the top like the comps.
Note: we need to do some cleanup on the API before this is ok to merge. (done 11/13)
Tested locally
Search results with:
Search results w/o:
Project Detail Page with:
Project Detail Page w/o:
> add support for displaying external accessions

- api/scpca_portal/templates/readme.md
- api/scpca_portal/templates/readme_multiplexed.md
#463 
Because we are now including an option to download files as either a SingleCellExperiment/RDS file or AnnData/HDF5 file, we no longer need the link to "What if I want to use Python" in the readme included with the RDS download. Also, the FAQ that is linked here, no longer exists in the docs so we want to remove it. 
I modified the main README and the multiplexed README to remove the link to the Python FAQ that no longer exists. 
> Remove links to python FAQ in READMEs used for SingleCellExperiment/RDS downloads

- api/scpca_portal/models/computed_file.py
- api/scpca_portal/test/management/commands/test_load_data.py
Resolves #552 
The `ComputedFile::has_bulk_rna_seq` and `ComputedFile::has_cite_seq_data` flags shouldn't be set for spatial modality.
> Do not set irrelevant attributes for spatial computed files

- api/scpca_portal/templates/readme.md
- api/scpca_portal/templates/readme_anndata.md
- api/scpca_portal/templates/readme_multiplexed.md
#457 
Here I added a line for the inclusion of the supplemental cell type report in all of the README's for downloads that should include this file. This applies to every download except for the spatial download. 
Note that I branched this off `feature/community-contributed-data` since cell types will be launched at the same time. 
Not applicable
> Account for supplemental cell type report in readme

- api/scpca_portal/serializers.py
- api/scpca_portal/test/factories.py
- client/src/components/Download.js
- client/src/components/DownloadOptions.js
- client/src/components/DownloadStarted.js
- client/src/config/downloadOptions.js
- client/src/helpers/hasMultiple.js
N/A
There were some things that needed to be cleaned up to have the AnnData changes laid on top. Notably, the `sample.multiplexed_with` was undefined, and this PR resolves that by adding to the serializer and updating the accessors on the client.
Additionally, as part of unbreaking staging before AnnData support is available, this PR will filter out AnnData computed files from presentation on the client side as they currently exist on staging. This change wont affect production and is safe to ship allowing us to support two different looking backends temporarily.
Also, this was a choice, I added a second parameter to the `hasMultiple` helper. This is optional and allows us to pass a filter function to be applied to the array before checking the length. I'm not concerned with this helper …
> Sample.additional_metadata.multiplexed_with has moved to Sample.multiplexed_with

- client/src/components/DownloadOptionsModal.js
- client/src/components/HelpLink.js
- client/src/contexts/DownloadOptionsContext.js
- client/src/hooks/useDownloadOptionsContext.js
n/a
This adds support for the Samples table modal to select users download options as well as the context for the updated project download flow. Those changes will be in a future PR.
N/A these should still be breaking until the project stuff lands.
n/a
> Adding new Ann Data Context and components

- client/src/components/AnnDataProcessingBanner.js
- client/src/components/Layout.js
- client/src/contexts/BannerContext.js
n/a
Adds a temporary banner to alert users that AnnData is currently being processed.
This banner is dismissible but will reappear on refresh.
n/a tested locally
> add ann data processing banner

- api/scpca_portal/templates/additional_terms_research_academic_only.md
- api/scpca_portal/templates/readme.md
- api/scpca_portal/templates/readme_anndata.md
- api/scpca_portal/templates/readme_multiplexed.md
- api/scpca_portal/templates/readme_spatial.md
Closes #482 
I am making two changes:
1. I created a template – `api/scpca_portal/templates/additional_terms_research_academic_only.md` – that contains the language we want to insert into READMEs included in downloads when a project is designated as research or academic purposes only. Note that I've used `H3` because I expect it to be inserted under the Terms of Use header (`H2`).
2. I've added `{additional_terms}` where I expect the template language to be inserted into every README. As mentioned, it's under the Terms of Use header.
> Add additional restrictions template for "research or academic purposes only" and where the language should go in READMEs

- api/scpca_portal/management/commands/load_data.py
N/A
I want to try processing some data from an alternative bucket. This PR adds an additional argument `--input-bucket-name` for the `load_data` command that will allow us to override the bucket that is used to pull data from.
This overrides the default the default value of `input_bucket_name` which is `scpca-portal-inputs`. 
Will create an issue to document this change.
Tested overriding locally, havent tested pulling from the staging bucket.
N/A
> Add input bucket as load data argument

- client/src/hooks/useScrollToTextContentHash.js
N/A
Merged PR: #555 at commit https://github.com/AlexsLemonade/scpca-portal/pull/555/commits/aee90af3176ee4b0dd48e11587dad3b44f7bd3e4
Now that the logic is decoupled from the `MarkdownPage` component,  I've update the `useScrollToTextContentHash` hook to take the dynamic value of y-coordinate as a parameter, and set the hardcoded value `-90` as the default value for that parameter.
Please see the latest UI [here](https://scpca-portal-i7e2fq0xs-ccdl.vercel.app/).
> Update the `useScrollToTextContentHash` hook to take dynamic y-coordinate position

- client/src/config/privacy-policy.md
Closes #584
I've update the link for the refine.bio terms to the ScPCA terms (absolute path) in [privacy-policy.md](https://github.com/AlexsLemonade/scpca-portal/blob/dev/client/src/config/privacy-policy.md?plain=1#L9).
Please see the latest UI [here](https://scpca-portal-r1vig30ba-ccdl.vercel.app/privacy-policy).
> 584 - Link to ScPCA Terms in Privacy Policy

- api/scpca_portal/templates/readme.md
- api/scpca_portal/templates/readme_anndata.md
- api/scpca_portal/templates/readme_merged.md
- api/scpca_portal/templates/readme_merged_anndata.md
- api/scpca_portal/templates/readme_multiplexed.md
- api/scpca_portal/templates/readme_spatial.md
Closes #582 
Here I'm adding two new template readmes, one for merged SingleCellExperiment objects and one for merged AnnData objects. The contents of which mostly mirror what's in the other readmes. The main difference here is in the `contents` section where I describe what files are included in the download. 
Just a note that I'm stacking this on `ark/549-add-merged-objects-support` as mentioned in #582. That branch does have an out of date readme, since the cell type report is not mentioned, but I assume it will eventually get merged in with where the cell type changes are, so I didn't fix any of the existing readmes to avoid any future conflicts. 
Also let me know if I should stack this on a different branch. 
- New feature (non-breaking …
> Add template readmes for merged objects 

- client/src/components/ProjectSamplesTable.js
> [!note]
> This PR can reviewed after the official AnnData deploy to `prod` (removing the AnnData loading banner), as it is a low priority.
Closing #603
Merged PR:
- #572 at commit https://github.com/AlexsLemonade/scpca-portal/pull/572/commits/242f7db8e812e3b946cfc223a13a5fcc906bbcdf
I've used the named import for the `useState` hook and removed the dot notation.
> 603 - Use the named import for the useState hook

- api/scpca_portal/models/computed_file.py
N/A
Per slack:
> It also looks like the readme being packaged with AnnData downloads is still the one for SingleCellExperiment objects.
This is a small change that sets the source template for the readme to be the `ComputedFile.README_ANNDATA_FILE_PATH` when a single-cell sample's computed file is being zipped up. This was correctly set for project but not for sample.
n/a
N/A
> Use ANNDATA readme for single-cell sample when format is ANNDATA

- api/scpca_portal/models/project.py
N/A
When generating samples for single-cell that also contain spatial data we were accidentally calling the spatial sample creation code with single-cell `AnnData` libraries. This was causing an error on the portal that made it look like we we're not generating single-cell `AnnData` samples.
Fixes single-cell anndata computed files when spatial present by "outdenting" the spatial computed file creation block so that it doesn't try and find spatial libraries on single-cell anndata directories.
This really should have a test for it, but realistically it would take a significant rewrite to ensure this code block isn't indented.
Please attach any screenshots …
> Move spatial samples outside of single-cell condition

- api/scpca_portal/views/filter_options.py
#527 #526 
Adds the new filter options to the `/project-options` endpoint.
Specifically:
- organisms
- models (includes_xenografts, includes_cell_lines)
This endpoint is only here until we switch over to elastic/opensearch. We could arguably move the hardcoded values for models to the project model but this is honestly fine for now.
Tested filtering on the projects that I have processed locally.
http://localhost:8000/v1/projects?includes_xenografts=true worked
http://localhost:8000/v1/projects?organismsHomo%20Sapiens worked
n/a
> Add community contrib filter options

- api/scpca_portal/migrations/0038_auto_20240320_2042.py
This is a fix for the staging database which currently has a migration applied which is no longer in the docker container's codebase. I assume that two deploys occurred in quick succession which led to a partially applied migration. Most likely the PR was reverted too quickly. The github action was finished but the deployment process was not complete.
Currently on staging this migration fails because the column already exists and the migration errors out so it can't be competed.
After this PR is merged, I will wait for the migrations to complete then revert the change. There will be no effect because the migration has already been applied so no additional changes will occur. However we want this to not be commented out when deploying to production which has no idea that this is happening. …
> temp comment out sample.is_cell_line migration

- api/scpca_portal/models/project.py
- api/scpca_portal/models/sample.py
- api/scpca_portal/test/management/commands/test_load_data.py
N/A
While testing the latest loaded project that contains spatial `SCPCP000006` to see if AnnData samples were being generated, I noticed that we were generating a `ComputedFile` for `single-cell` `SingleCellExperiment` on spatial only samples. This was due to an old assumption that `single-cell` would always exist for every sample.
This PR adds in 2 main changes:
- Add `Sample.single_cell_file_types` which does what it says on the label. It checks against the sample's properties for supported file types (anndata/sce) and is evaluated to a list that contains the correspoding `ComputedFile.OutputFileFormats` value. If no single-cell is available this property is evaluated as an empty array.
- Changes Project.load_data to iterate off of this value instead of the default …
> Check if single-cell SingleCellExperiment data exists before creating a computed file

- api/scpca_portal/models/computed_file.py
- api/scpca_portal/templates/readme/multiplexed.md
#627 
This is the temporary fix for #627 
This change checks if the cell type report exists and only if it does will it try to copy over to output zip.
Additionally, the readme has been updated to reflect that multiplexed files do not contain cell type reports.
N/A tested locally
N/A
> remove celltype reports from multiplexed

- client/src/pages/privacy-policy.js
N/A
I've temporarily added this fix to the Privacy Policy markdown to remove the old date (the 1st line of the screenshot - highlighted).
The last updated date should match the value of the env var `PRIVACY_POLICY_RELEASE` which is the latest deploy date (the 2nd line of the screenshot). 
(screenshot via `prod`)
Please see the latest UI [here](https://scpca-portal-1rpvzbji2-ccdl.vercel.app/privacy-policy). 
@davidsmejia I see that both env vars `PRIVACY_POLICY_RELEASE`  and `TOS_RELEASE` values were updated to `April 7th, 2024` in Vercel 2 days ago. 
For the Terms of Use's markdown content, the old last updated date was commented out but the Privacy Policy. So I added this quick fix to remove the old date. Or please let me know otherwise.
We'll either: 
- Comment out the `LastUpdated` …
> Fix - Remove the duplicated Last Updated line from the Privacy Policy page

- api/scpca_portal/management/commands/load_data.py
[#367](https://github.com/AlexsLemonade/scpca-portal/issues/367)
- Added default value of `False` to `--reload-all` and `--reload-existing` flags, in order that they should default to the anticipated `False` value, and not to type `None`. 
> Aside: This is also meant to clarify the convention for the `load_data` script flags of type `Boolean`, where all non environment dependent[^1] default values fall back on `False`, while the caller is given the ability to explicitly override this functionality when desired by passing the flag to the command. With those flags that do have environment dependent default values, we use the `argparse.BooleanOptionalAction` action, which creates a unified interface for both `--arg` and `--no-arg` to be handled by the command, irrespective of the …
> 367 - Improve load data script flags handling

- api/scpca_portal/models/computed_file.py
- api/scpca_portal/models/project.py
N/A
Main changes:
- Prevent deleting a multiplexed sample after one thread had created it so that it can be used when specifying to clean up output data, we clean up zips after created and every other file after the load_data script has completed. This is a problem for multiplexed because we re-use those files when processing the `multiplexed_with` samples.
- Make the checking of if a computed file exists thread safe. When creating multiplexed samples we reuse a computed file if it is already there. I added a change that creates a lock for each group of samples that are multiplexed together. This prevents a subsequent thread from trying to interpret the state of the generated zip before it is finished being written to.
Other notes:
- Our current implementation of concurrent processing of …
> Fix multiplexed sample computed file generation when using multiple threads

- api/scpca_portal/models/project.py
- api/scpca_portal/test/management/commands/test_load_data.py
N/A This is a temp change while we initially process merged objects.
We want to process merged objects on the API before making them available on the portal.
This change omits merged computed files for projects until we deploy the functionality to handle them on the client side.
This change will be removed in a subsequent PR.
N/A
N/A
> Temp: omit project merged computed files

- api/scpca_portal/models/project.py
- api/scpca_portal/test/management/commands/test_load_data.py
N/A
Production has been deployed so we can add this back in on staging to test the client updates.
This just removes the filter that omited project.computed_files from including computed_files where includes_merged is true.
n/a
N/A
> Remove temp omission of merged computed files on project

- client/src/config/index.js
N/A
Tested the docs links against the preview before they are released. Linking to the FAQ section for `Which projects can I download as merged objects?` was incorrect. This PR addresses that.
N/A
N/A
> Fix fragment on which projects are merged docs link

- api/scpca_portal/models/computed_file.py
- api/scpca_portal/models/project.py
- api/scpca_portal/test/management/commands/test_load_data.py
#667 
Honestly, this was just as simple as:
- pointing to the new test data bucket key `2024-04-19`
- Search replace of `hdf5` with `h5ad`
The tests pass and this is good to test on staging.
Note: This PR does *not* contain any updated markdown.
N/A
N/A
> AnnData extensions change hdf5 -> h5ad

- api/scpca_portal/views/computed_file.py
N/A
Adds the `has_mutliplexed_data` attribute to the `ComputedFile` serializer. We are ready to do the FE updates so this is needed now.
n/a
n/a
> Add has_multiplexed_data to computed file serializer

- api/scpca_portal/serializers.py
- api/scpca_portal/test/serializers/test_computed_file.py
N/A
Adds `has_multiplexed_data` to a project or samples related computed files.
This was previously added only to the Serializer for authenticated requests.
n/a
N/A
> Add has_multiplexed_data to related computed files

- client/src/components/ProjectSamplesTable.js
- client/src/components/Table.js
#557 
This PR addresses the functionality of sorting the samples table by the size of the download when clicking the arrows on the column header.
- Makes the arrows functional on the download column and sorts in order of:
-  download size
- if the sample is available in a different format
- if the sample is not downloadable last
N/A sorted locally
> Sort samples download size

- client/src/hooks/useDownloadModal.js
N/A
When selecting `Download Now` again (without refreshing) the previously configured download would automatically trigger. This was not the expected behavior. We now clear out the public computed file after downloading so that users can select new download options without refreshing.
- Conditionally set `publicComputedFile` to null when not specified on modal open
- Loosen constraint that `publicComputedFile` be defined to show `DownloadStarted` state.
- This should be fine because `download` must be true which implies `publicComputedFile` was correctly defined at some point in the hooks's lifecycle
N/A
N/A
> Allow downloading of multiple configuration options

- api/scpca_portal/models/project.py
- api/scpca_portal/test/management/commands/test_load_data.py
N/A
We recently added new options for available downloads for projects that contain multiplexed samples.
- Single-cell as Single-cell Experiment/Single-cell as AnnData
- Only non-multiplexed samples
- `samples_metadata.tsv` will only contain non-multiplexed sample libraries
- Single-cell as Single-cell Experiment w/ Multiplexed samples
- Will contain non-multiplexed samples and multiplexed samples alike
- `samples_metadata.tsv` will only contain all single-cell samples libraries metadata
This PR essentially takes the previously generated Single-cell non-multiplexed samples metadata and concatenates it with the multiplexed metadata libraries before writing to disk. During write the rows are sorted by `scpca_sample_id` first and `scpca_library_id` second.
- Bugfix (non-breaking change which …
> Combine non-multiplexed and multiplexed metadata for project `samples_metadata.tsv`

- client/src/components/Logo.js
Closing #649
I've set the `width: 91px` to the ALSF logo to prevent it from flashing on page load/refresh.
Please see the latest UI [here](https://scpca-portal-jsdsi75v1-ccdl.vercel.app/).
> 649 - Fix the ALSF logo flash on page load/refresh

- api/scpca_portal/models/project.py
- api/scpca_portal/test/test_utils.py
- api/scpca_portal/utils.py
https://github.com/AlexsLemonade/scpca-portal/issues/693
Prior to this PR, 
- the combining of sample and library metadata dictionaries, and 
- the writing of those combined libraries to sample and project metadata tsv files 
lived together inside `Project::combine_metadata`. 
In order to decouple these two actions, all file writing logic within `Project::combine_metadata` was removed and placed into a new method called `Project::write_combined_metadata_libraries`. 
The new execution of `Project::load_data` looks as follows 
- Readmes are generated
- `Project::handle_samples_metadata` is called, which parses and combines sample and library metadata, and returns the `combine_metadata` libraries
- Directly afterwards, `Project::write_combined_metadata_libraries` is called, taking the …
> 693 - Extract metadata file writing from combine metadata

- api/scpca_portal/common.py
- api/scpca_portal/management/commands/load_data.py
- api/scpca_portal/models/contact.py
- api/scpca_portal/models/external_accession.py
- api/scpca_portal/models/project.py
- api/scpca_portal/models/publication.py
- api/scpca_portal/test/test_utils.py
- api/scpca_portal/utils.py
https://github.com/AlexsLemonade/scpca-portal/issues/694
This PR addresses a design improvement of moving the assignment of project-level properties (to the active project object) from the `load_data` command to `Project::load_data`. 
From an implementation perspective, the necessary changes include moving the `load_data::process_project_data` function to the `Project` model, and sending in, as an additional argument to `Project::load_data`, the project-level properties dictionary (which is parsed from the top-level `project_metadata.csv` file that `load_data::load_data` uses to create the `Project` objects to begin with).
N/A
N/A
> 694 - Move project property assignments from load_data command to Project model

- api/scpca_portal/management/commands/load_data.py
N/A
During the recent refactor of `Project::load_data`, project property assignments, which were previously carried out inside of `load_data::load_data`, were converted into a factory method and moved to the project model. During this refactor, all references to `self.project` were removed. It came up that one reference was left by accident, inside of `load_data::clean_up_input_data`, and that is what was cleaned up in this PR.
N/A
N/A
> Remove left over reference to self.project in load_data::clean_up_input_data

- client/src/components/ProjectHeader.js
N/A
As a general policy we should prevent the client from breaking entirely on the browse page when data is malformed.
When loading a specific project (or currently if a project is partially processed) it is possible for `seq_units` to be `null` though we shouldn't really expect this to be the case. This PR adds a fallback to a value that is parsed on the client.
Specifically here, If one project has `seq_units` null then the client crashes making it impossible to download any projects.
I think a future and more robust fix would be having a type of state attribute on the project model that allows us to filter out processing or malformed projects via the API endpoint so only "good" projects are returned. This fix would safely be removable at that point. 
- Bugfix (non-breaking change which …
> Hotfix: add check for seq-units

- api/scpca_portal/common.py
- api/scpca_portal/test/management/commands/test_load_data.py
- api/scpca_portal/test/test_utils.py
Closing #729 
I've added the new ontology columns to `METADATA_COLUMN_SORT_ORDER` and adjusted the tests. 
**Question:** should we remove those newly added ontology columns from the expected additional metadata keys in `TestLoadData`? Thank you, David!
> 729 - Add new ontology columns to METADATA_COLUMN_SORT_ORDER list

- api/scpca_portal/models/library.py
- api/scpca_portal/models/project.py
- api/scpca_portal/models/sample.py
- api/scpca_portal/test/management/commands/test_load_data.py
https://github.com/AlexsLemonade/scpca-portal/issues/711
This PR takes the creation the `Library` model forward from PR https://github.com/AlexsLemonade/scpca-portal/pull/720 and begins to implement it. 
The following three items are included in the current PR:
- `Library::get_from_dict` and `Library::bulk_create_from_dicts` methods are built, similar to those in the `Sample` model. These methods are responsible for building a collection of new `Library` objects, and saving them to the db.
- The building of `Library` objects is added to `Project::load_libraries_metadata`. In order to accommodate this, the building and creating of `Sample` objects is moved from the end of `Project::handle_samples_metadata` to `Project::load_samples_metadata`, which in any case is a more appropriate place …
> 711 - Create library model factory method and add it to Project::load_data

- api/scpca_portal/models/computed_file.py
N/A
Hotfix to address the possibility that a computed file may not have a modality when the str dunder method is called. This was preventing uploads of metadata only downloads.
N/A
n/a
> make computed file str method safe for no modality

- api/scpca_portal/models/computed_file.py
- api/scpca_portal/templates/readme/metadata_only.md
#738 
- The readme template for metadata only downloads didn't handle the list of projects correctly when a single project was being created, this fixes that by putting it in a loop (that iterates one time).
- `computed_file.metadata_file_name` was returning `None` when the modality wasn't set. This was addressed by having a default of `metadata.tsv` so we don't end up copying the entire source path into the zip file.
N/A
N/A
> Project Metadata Download Feedback

- client/src/components/ProjectSamplesTable.js
N/A
- Fix for issue on samples table
- when there is no metadata file to download, disable the button
N/A
n/a
> fix for enabled download button when not there

- api/scpca_portal/models/project.py
- api/scpca_portal/models/sample.py
https://github.com/AlexsLemonade/scpca-portal/issues/740
- Added `Project::create_computed_files` and `Sample::create_computed_files` methods, which utilize iteration over prebaked download configuration to kick of a ThreadPoolExecutor which creates computed files in parallel.
- Added `Project|Sample::get_download_config_file_output_name` method for dynamic naming of zip files.
- Added `Sample::get_lock_name` utility method to abstract lock naming logic.
N/A
N/A
> 740 - Project and Sample Create Computed Files Driver Methods

- api/scpca_portal/common.py
- api/scpca_portal/metadata_file.py
- api/scpca_portal/models/library.py
- api/scpca_portal/models/sample.py
- api/scpca_portal/test/management/commands/test_load_data.py
https://github.com/AlexsLemonade/scpca-portal/issues/778
- Rename `sample_cell_estimates` attribute to `sample_cell_estimate`.
- Exclude `sample_cell_estimates` key from being passed through from `library.metadata` in `Library::get_metadata`
- Include `sample_cell_estiamate` key from Sample model, which pulls from the `Sample.demux_sample_cell_count` (which is updated in Project::update_sample_aggregate_values`
- Update `restval` in `metadata_file::write_metadata_dicts`
Note about addition of `restval`:
- The reason that the updating of the `restval` property of `metadata_file::write_metadata_dicts` is in this PR is because we have to assume that projects with multiplexed libraries will also have samples with non multiplexed libraries. As such, both `sample_cell_count_estimate` and …
> 778 - Presenting sample sample_cell_estimates per sample in output metadata file

- api/scpca_portal/test/test_utils.py
- api/scpca_portal/utils.py
N/A
`utils::list_s3_paths` had a bug in it which prevented it from adequately handling non-recursive paths. 
I've fixed that bug while also adding a new test which tests non-recursive paths.
`test_utils::TestListS3Paths::test_list_s3_paths_non_recursive_path`
N/A
> Hot fix - bug in non-recursive paths in utils::list_s3_paths

- api/scpca_portal/models/computed_file.py
- api/scpca_portal/models/project.py
- api/scpca_portal/models/sample.py
https://github.com/AlexsLemonade/scpca-portal/issues/742
This PR deals with the breaking up of `ComputedFile::process_computed_file` into two methods:
- `ComputedFile::upload_s3_file`
- `ComputedFile::clean_up_local_computed_file`. 
The calling of these methods is moved outside of a wrapper (like the role that `ComputedFile::process_computed_file` played), and are called directly inside of `Project::create_computed_files::on_get_project_file` and `Sample::create_computed_files::on_get_sample_file` after computed files have been generated and `computed_file` objects have been created and returned.
As a note - a check has been included before the uploading and cleaning up of local files that makes sure that files are only uploaded and cleaned up once. This is especially a point of concern …
> 742 - Break up ComputedFile::process_computed_file

- api/scpca_portal/metadata_file.py
- api/scpca_portal/models/computed_file.py
- api/scpca_portal/test/management/commands/test_load_data.py
- api/scpca_portal/test/test_metadata_file.py
https://github.com/AlexsLemonade/scpca-portal/issues/784
- Replace eager writing of `output_metadata_file` to a local file (before zip archival) with writing it to an in memory buffer (during zip archival)
- The file is written to the buffer and thereafter immediately written to the zip archive
- Move metadata output file naming logic out of zip archival process in `ComputedFile::get_project|sample_file` and into own method inside of `metadata_file` module called `metadata_file::get_metadata_file_name`
- Move MetadataFilenames constants from `ComputedFile` model to `metadata_file` module
- Update `metadata_file::write_metadata_dicts` to handle writing to a buffer
N/A
N/A
> 784 - In memory metadata file generation

- api/scpca_portal/management/commands/create_portal_metadata.py
- api/scpca_portal/test/management/commands/test_create_portal_metadata.py
- bin/sportal
#797 
This is the 1st item in the stacked PR list for the linked issue.
The following changes are included:
- Added the `create-portal-metadata.py` file
- Added the `create-portal-metadata.py` file  which setup the database by calling `load_data`
- Added the `create-portal-metadata` command to `sportal`
N/A
N/A
> 797 - Scaffolding the porta-wide metadata management command and test files

- api/scpca_portal/config/common.py
N/A
I was debugging the staging database when I needed some commands that are present in django_extensions. We already include this module in our base requirements so this is just a matter of telling django to include it on start.
N/A
N/A
> add django extensions to installed apps

- api/scpca_portal/migrations/0047_library_project.py
N/A
Mainly what it says on the tin. Migration `0047_library_project` wasn't able to be run against a populated database because the new column's value was undefined at creation. This PR essentially makes the column nullable at creation, iterates over any libraries to populate that value, then restricts the column to make it non nullable again.
Additionally, I added support to roll back the custom migration to allow for testing.
Populated the db with test data from the previous deployment. Then ran the migration to recreate the error.
N/A
> Make Library.project nullable during migration

- api/scpca_portal/models/project.py
N/A
This is a fix for a specific type of situation that we do not expect to encounter regularly. It seems prudent to include at this time because it is difficult to surface when an error occurs when reloading the portal as the output is pretty verbose and takes a long time. I don't expect myself or anyone else to sit there and watch the terminal for the duration of loading data.
The problem occurs when there is a PROJECT_ID/SAMPLE_ID/LIBRARY_ID_metadata.json file present when `SAMPLE_ID` is not present in `PROJECT_ID/samples_metadata.csv`. The error occurs when we try and fetch a Sample based on the ID present in the library metadata and it does not exist.
This fix conditionally creates the library only if the sample id present in the library metadata exists in the database.
- Bugfix …
> Ensure sample exists before creating library

- api/scpca_portal/models/project.py
- api/scpca_portal/models/sample.py
N/A
We need to ensure that the filename user's download matches what is contained in our own documentation as to not confuse users. This change should be included in the next portal release and synchronized with the next documentation release as well.
N/A
N/A
> Update download filename to match the portal documentation.

- infrastructure/database.tf
#848 
Known error occurring in terraform where the `latest_valid_till` argument is returning multiple certs and the aws provider does not know what to do. There is an open issue here: 
I'd like to test if a rename works, If this does not work, I will open a PR for setting a specific version.
N/A
N/A
> update cert name: latest -> cert

- infrastructure/database.tf
#848
Unable to get the `latest_version_till` to resolve a single certificate in a reasonable amount of time. This may be looked into in the future but this certificate will expire in the 2060's which seems sufficient.
N/A
N/A
> Explicitly set RDS CA: rds-ca-rsa2048-g1

- api/scpca_portal/s3.py
N/A
- Fixes error with default bucket name's incomplete name
N/A
N/A
> fix setting name AWS_S3_BUCKET_NAME

- .github/workflows/push.yml
- api/scpca_portal/metadata_file.py
- api/scpca_portal/test/factories.py
- api/scpca_portal/test/test_metadata_file.py
- bin/sportal
- recreate_schema.sh
- run_psql_client.sh
https://github.com/AlexsLemonade/scpca-portal/issues/816
Refactor the following tests in `test_metadata_file::TestGetFileContents`:
- `setUp`
- `test_get_file_contents_successful_write`
- `test_get_file_contents_read_write_values_match`
Add additional tests in `test_metadata_file::TestGetFileContents`:
- `test_get_file_contents_multi_value_field`
- `test_get_file_contents_missing_value`
- `test_get_file_contents_missing_field_name`
- `test_get_file_contents_sort_order`
Additional changes introduced include:
- Populating metadata attribute in `factories::LibraryFactory` lazily to overcome sharing of attribute among all library factory instances.
- Handling transformation of `None` or empty string `""` values to `NA` when prepping metadata for writing in …
> 816 - Refactor Tests for metadata_file::get_file_contents

- api/scpca_portal/management/commands/generate_computed_files.py
- api/scpca_portal/management/commands/load_data.py
- api/scpca_portal/models/project.py
- api/scpca_portal/test/management/commands/test_generate_computed_files.py
- api/scpca_portal/test/management/commands/test_load_data.py
https://github.com/AlexsLemonade/scpca-portal/issues/842
Added a placeholder for the `generate_computed_files` command. Currently, the command take the functionality of the `load_data` command, as it pertains to the creation of a project's computed files.
This command will serve as the entry point for Batch instances, generating all of a passed project's computed files (according to a predetermined collection of download configs), and uploading them to s3.
N/A
N/A
> 842 - Add placeholder generate_computed_files command

- api/scpca_portal/models/project.py
- api/scpca_portal/models/sample.py
N/A though related to #898
The goal of this PR was to correctly sum multiplexed libraries sample counts located in the library's metadata json file attribute `sample_cell_estimates`. This dictionary contains the partial number for each sample and needs to be summed up when assigning `demux_cell_count_estimate` on a multiplexed sample.
Additionally, I updated the evaluation of `sample.multiplexed_with` to use a new property `sample.multiplexed_with_samples` under the hood. This was a change for clarity and ultimately does the same as the original implementation.
Coverage for this change will be available once `feature/loader` is merged into dev.
**Edit** see comment below about test coverage.
- Loaded SCPCP000009 locally and looked at the …
> Sum estimated demux sample counts

- api/scpca_portal/config/local.py
- api/scpca_portal/metadata_file.py
- api/scpca_portal/models/project.py
- api/scpca_portal/test/expected_values/project_SCPCP999990.py
- api/scpca_portal/test/expected_values/project_SCPCP999991.py
- api/scpca_portal/test/expected_values/project_SCPCP999992.py
- api/scpca_portal/test/views/test_filter_options.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/903
This PR updates the test bucket from `scpca-portal-public-test-inputs/2024-07-19/` to `scpca-portal-public-test-inputs/2024-09-10/`.
In order to accommodate the change in how the `Project` attribute `diagnoses` is handled, a `PROJECT_METADATA_VALUES_TRANSFORMS` constant and `transform_values` helper function were added to `metadata_file`.
Values in the `expected_values/` files were also updated in order to match any changed values in the metadata files in the new test bucket.
N/A
N/A
> 903 - Update Test Bucket to 2024-09-10

- api/scpca_portal/common.py
- api/scpca_portal/templates/readme/contents/METADATA_ONLY.md
- api/scpca_portal/test/expected_values/computed_file_project.py
- api/scpca_portal/test/expected_values/readmes/ALL_METADATA.md
- api/scpca_portal/test/expected_values/readmes/PORTAL_ALL_METADATA.md
- api/scpca_portal/test/expected_values/readmes/SINGLE_CELL_ANN_DATA.md
- api/scpca_portal/test/expected_values/readmes/SINGLE_CELL_ANN_DATA_MERGED.md
- api/scpca_portal/test/expected_values/readmes/SINGLE_CELL_SINGLE_CELL_EXPERIMENT.md
- api/scpca_portal/test/expected_values/readmes/SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MERGED.md
- api/scpca_portal/test/expected_values/readmes/SINGLE_CELL_SINGLE_CELL_EXPERIMENT_MULTIPLEXED.md
- api/scpca_portal/test/expected_values/readmes/SPATIAL_SINGLE_CELL_EXPERIMENT.md
- api/scpca_portal/test/factories.py
- api/scpca_portal/test/test_readme_file.py
Closes #902
Feature branch: `feature/loader`
Base branch:  the latest `feature/loader` (#896)
I've added the dedicated `test_readme_file` to support complete coverage of all readme file variations for each computed file type by project ID.
Changes includes:
- Add `test/test_readme_file`
- Added saved readme files in `test/expected_values/readmes`
- Added a new constant `common.EXPECTED_VALUES_PATH` (for the `expected_values` folder)
- Adjust `templates/readmes/contents/METADATA_ONLY.md`
Other changes:
- Adjusted `test/factories` to generate five-character prefixes followed by six-digit IDs, and fix a typo
- Adjust the assertion values in `test/expected_values/computed_file_project`for test
- New feature …
> 902 - Add test_readme_file for readme tests 

- api/manage.py
- api/scpca_portal/common.py
- api/scpca_portal/config/__init__.py
- api/scpca_portal/config/common.py
- api/scpca_portal/config/local.py
- api/scpca_portal/config/production.py
- api/scpca_portal/config/test.py
- api/scpca_portal/loader.py
- api/scpca_portal/management/commands/create_portal_metadata.py
- api/scpca_portal/metadata_file.py
- api/scpca_portal/models/computed_file.py
- api/scpca_portal/models/library.py
- api/scpca_portal/models/project.py
- api/scpca_portal/models/sample.py
- api/scpca_portal/readme_file.py
- api/scpca_portal/s3.py
- api/scpca_portal/test/management/commands/test_create_portal_metadata.py
- api/scpca_portal/test/management/commands/test_generate_computed_files.py
- api/scpca_portal/test/test_loader.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/862
This PR adds a `config` module for the testing environment. It inherits from the `local` config module, but changes the `AWS_S3_INPUT_BUCKET_NAME` to the `test_bucket`, and updates the `DATA_PATH` attribute to point to `CODE_PATH / "test_data"`.
As well, this PR moves environment based constants from `common.py` to the `config` modules.
N/A
N/A
> 862 - Create config/test Module

- api/scpca_portal/common.py
- api/scpca_portal/models/library.py
- api/scpca_portal/models/sample.py
- api/scpca_portal/test/expected_values/computed_file_project.py
- api/scpca_portal/test/expected_values/computed_file_sample.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/921
This PR removes the Sample attribute `sample_cell_count_estimate` from the output metadata file.
N/A
N/A
> 921 - Remove sample_cell_count_estimate from metadata output

- infrastructure/networking.tf
- infrastructure/provider.tf
Closes https://github.com/AlexsLemonade/scpca-portal/issues/918
This PR moves the AWS provider terraform code block from `infrastructure/networking.tf` to its own file in `infrastructure/provider.tf`. The version is also updated to 5.12.0 in order to allow for usage of newer features utilized in the new Batch implementation.
N/A
N/A
> 918 - Move and update provider block

- client/src/components/ContributeClosedCard.js
N/A
Does what it says.
This was just missed during review because it wasn't edited. But previously we must have been editing the config link and to correctly send someone to the interest form vs the intake form so here we accidentally were still linking them to the intake form. 
N/A
N/A
> Link to interest form on the "Contributions Closed" card.

- api/scpca_portal/loader.py
- api/scpca_portal/management/commands/dispatch_to_batch.py
- api/scpca_portal/management/commands/generate_computed_file.py
- api/scpca_portal/models/computed_file.py
- api/scpca_portal/models/project.py
- api/scpca_portal/models/sample.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/915 and https://github.com/AlexsLemonade/scpca-portal/issues/841
This PR makes 3 additions
- Adds a `loader::generate_computed_file` method
- Adds a `generate_computed_file` management command, which will be used as the entrypoint with Batch jobs
- Adds a `dispatch_to_batch` management command, responsible to iterating over all permutations of projects, samples and downloads_configs which need computed files generated for them
- Breaking change (fix or feature that would cause existing …
> 915 - Add generate computed file command

- api/scpca_portal/models/project.py
- api/scpca_portal/test/expected_values/project_SCPCP999990.py
- api/scpca_portal/test/expected_values/project_SCPCP999991.py
- api/scpca_portal/test/expected_values/project_SCPCP999992.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/879
The `Project`  attribute `unavailable_samples_count` was being set after computed file generation, although this value was known at the end of the loading of metadata. This PR moves the setting of this attribute to its correct location.
There was also a bug in how this attribute was being set that was handled in this PR.
N/A
N/A
> 879 - Update setting of Project::unavailable_samples_count

- api/Dockerfile.local
- api/Dockerfile.prod
#950
Production deployments are currently unable to be build via github actions. This PR pins the base image to 3.10.14 to see if builds may be resumed. If it works we can create a new issue to debug further after deploying the latest data to the portal.
N/A
N/A
> Lock Docker base image to python 3.10.14

- api/scpca_portal/loader.py
- api/scpca_portal/management/commands/dispatch_to_batch.py
- api/scpca_portal/models/computed_file.py
- api/scpca_portal/models/project.py
- api/scpca_portal/test/expected_values/computed_file_sample.py
- api/scpca_portal/test/test_loader.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/943
This PR addresses the suboptimal implementation for multiplexed sample computed files as it pertains to AWS Batch. As mentioned in the connected issue, the current approach utilizing a lock is only possible on a single machine where multiple threads are vying for compute resources. When each sample and download_config is broken up into a separate job, multiplexed samples will be recomputed and re-uploaded on each machine that the job runs on, which is wasteful and unnecessary.
This PR makes the following changes:
- Adds a Project::all_samples_no_multiplexed_duplicates property method which allows for querying of all non multiplexed samples and one multiplexed sample per multiplexed library in the caller.
- Removes the locking …
> 943 - Fix Multiplexed for Batch

- .github/workflows/deploy_prod_backend.yml
- .github/workflows/deploy_staging_backend.yml
Closes https://github.com/AlexsLemonade/scpca-portal/issues/964
This PR updates the TF version in the GHA workflows from `0.12.26` to the newest version, `1.9.8`. 
Spinning up a devstack with this new version was successful.
The `actions/checkout` action was also updated by `v2` to `v4`.
N/A
N/A
> 964 - Update Terraform version in GHA Workflows

- .github/workflows/deploy_prod_backend.yml
- .github/workflows/deploy_staging_backend.yml
There is an intermediate step when upgrading from TF 0.12.x to 1.x.x.
TF will automatically apply `terraform 0.13upgrade`, which should resolve the `Invalid legacy provider address` error.
First we'll upgrade to 0.13.x, and then transition to 1.x.x.
Discussion here - https://discuss.hashicorp.com/t/unqualified-provider-aws/18554
Upgrade steps -https://developer.hashicorp.com/terraform/language/v1.1.x/upgrade-guides/0-13
N/A
N/A
> Downgrade to Terraform 0.13.0 in Github GHA workflows

- infrastructure/database.tf
- infrastructure/networking.tf
- infrastructure/permissions.tf
We updated here the errors from tags being duplicated, likely due to them being included in the provider block as well as where resources were defined.
We've left the deprecation warning `acl="private"` in place for now, and will handle it later.
N/A
N/A
N/A
> Remove identical default tags definitions as they're already included in the provider block

- .github/workflows/deploy_prod_backend.yml
- .github/workflows/deploy_staging_backend.yml
- infrastructure/provider.tf
As we're updating the aws provider version to 5.x, we encountered a challenge in upgrading from 4.x to 5.x. According to the 4.0 release changelog https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/tag/v4.0.0, we should be transitioning from tf 0.13.x to 1.0.x. This PR does just that.
N/A
N/A
N/A
> Upgrade terraform version to 1.0.8

- infrastructure/replace_provider.py
Describe the big picture of your changes.
> Add auto-approve to replace_provider command

- infrastructure/deploy.py
N/A
Deploys look like they are failing but they are fine. This issue is caused by upgrading to terraform 0.14.0 where
output strings are wrapped in quotes. This PR updates our regex to account for them.
N/A
N/A
> add quotes to regex for terraform outputs

- .github/workflows/deploy_prod_backend.yml
- .github/workflows/deploy_staging_backend.yml
- infrastructure/provider.tf
N/A
- Upgrades terraform to 1.0.8 so that we can upgrade aws provider to 5.x.x
N/A
N/A
> upgrade to terraform 1.0.8

- infrastructure/deploy.py
- infrastructure/s3.tf
N/A
-  Addresses s3 bucket lifecycle deprecation warning
- uses json outputs for terraform to prevent parsing issues
N/A
N/A
> terraform 1.0.8 updates

- infrastructure/deploy.py
- infrastructure/provider.tf
N/A
- upgrade terraform aws provider to latest 5.x.x
- adds back terrform outputs to see deprecation warnings etc.
N/A
N/A
> upgrade terraform aws provider to latest 5.x.x

- infrastructure/batch/job_queue.tf
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1012
This PR fixes the deprecation warning regarding how compute_environments are defined inside of job_queue modules in Terraform which was updated in aws_version 5.x.
N/A
N/A
N/A
> 1012 - Fix job_queue compute_env Deprecation Warning

- api/scpca_portal/common.py
- api/scpca_portal/test/test_utils.py
- api/scpca_portal/utils.py
Closes #1041
Change includes:
- Added `NA` to `common.IGNORED_INPUT_VALUES`
- Added a fallback `""` for missing keys in `utils.get_csv_zipped_values`
- Replaced `AttributeError` with `ValueError` in `test_get_csv_zipped_values_keys_not_present`
N/A
N/A
> 1041 - Add `NA` to common.IGNORED_INPUT_VALUES for Publication and ExternalAccession links

- api/scpca_portal/management/commands/dispatch_to_batch.py
- api/scpca_portal/test/factories.py
- api/scpca_portal/test/management/commands/test_dispatch_to_batch.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1025
Add a test module for `dispatch_to_batch` which tests correct project querying and job submission.
Update `ProjectFactory` factory method to adequately handle the library and sample relationship.
- `test_dispatch_to_batch`
- `test_only_projects_without_computed_files_submitted`
- `test_project_id_submission`
N/A
> 1025 - Add test_dispatch_to_batch

- infrastructure/batch.tf
- infrastructure/batch/job_definition.tf
- infrastructure/secrets.tf
N/A
This is a security hygiene improvement. While I was digging through our batch implementation this morning I came across some internally exposed credentials. This PR moves the sensitive envars from `environment` to `secrets` when creating the batch job definition container properties. This change should land before cycling the sensitive values later today.
N/A
N/A
> batch secrets

- infrastructure/batch/job_definition.tf
#959 
By default custom tags are not passed from the job definition to individual jobs/tasks. This PR forces the job/task's tags to be assigned at time of creation from the job_description.
Note: propagated tags do not take priority and may be overridden at time of job/task creation.
N/A 
terraform validate passed
N/A
> propagate tags from aws_batch_job_definition

- api/scpca_portal/test/management/commands/test_sync_original_files.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1049.
Add testing for sync_original_files command which tests
- creating files
- updating files
- deleting a single file
- attempting to delete all files without passing the `--allow-bucket-wipe` flag
- deleting all files while passing the `--allow-bucket-wipe` flag
- `test_sync_original_files`
N/A
> 1049 - Add test_sync_original_files module

- infrastructure/batch/roles.tf
#1069 
Does what it says on the tin
- creates policy that allows access to read secrets from secrets manager
- attaches policy to batch job role
`terraform validate`
N/A
> 1069 - Add and attach batch job secretsmanager access policy

- infrastructure/batch/roles.tf
#1069 
Apparently terraform validate doesn't evaluate json strings, terraform plan should be done instead.
N/A
N/A
> add missing comma to secretsmanager policy

- infrastructure/database.tf
#1071 
As per their documentation max minor version on 16 is actually 16.3 when upgrading from 12.19
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.MajorVersion.html
N/A
N/A
> Max upgrade minor version 16.3 - 12.19 -> 16.3

- infrastructure/batch/roles.tf
#1069 
As per the error, the permissions that were missing were on the ecs task role and not the batch job role. This PR moves that attachment off of the batch job role and onto the ecs task role.
N/A
N/A
> Attach policy to ecs task role off of batch job role

- infrastructure/database.tf
#1071 
- adds instructions on commenting out `allow_major_version_upgrade` and `apply_immediately` when not in the process of upgrading db version
- sets`apply_immediately` to true on rds instance
N/A
N/A
> Add upgrade instructions and apply immediately to database instance

- infrastructure/database.tf
#1071 
- removes parameter group for postgres v12.xx
N/A just removing dead infrastructure
N/A
> Remove old parameter group and lock version upgrades

- api/scpca_portal/enums/__init__.py
- api/scpca_portal/enums/file_formats.py
- api/scpca_portal/models/dataset.py
- api/scpca_portal/models/library.py
- api/scpca_portal/models/project.py
- api/scpca_portal/test/expected_values/project_SCPCP999990.py
- api/scpca_portal/test/expected_values/project_SCPCP999991.py
- api/scpca_portal/test/expected_values/project_SCPCP999992.py
- api/scpca_portal/test/factories.py
- api/scpca_portal/test/models/test_sample.py
Closes #1065
I've moved the inner class `FileFormats` from the following models to `enums/file_formats.py` and updated all the references:
- `Dataset`
- `Library`
N/A
N/A
> 1065 - Move FileFormats to enums/file_formats.py

- api/scpca_portal/management/commands/dispatch_send_test_email.py
Remove illegal white space in Batch job name
N/A
N/A
> Fix no white space in Batch job name error

- api/scpca_portal/management/commands/dispatch_send_test_email.py
Remove illegal characters from Batch job name
N/A
N/A
> Fix no special characters in batch job name error

- api/scpca_portal/enums/file_formats.py
- api/scpca_portal/enums/job_states.py
- api/scpca_portal/enums/modalities.py
- api/scpca_portal/models/dataset.py
- api/scpca_portal/models/job.py
- api/scpca_portal/models/library.py
- api/scpca_portal/models/original_file.py
- api/scpca_portal/models/sample.py
- api/scpca_portal/test/expected_values/project_SCPCP999990.py
- api/scpca_portal/test/expected_values/project_SCPCP999991.py
- api/scpca_portal/test/expected_values/project_SCPCP999992.py
Close #1106
I've updated all the classes in the `enums` folder to be subclasses of `Enum`.
Regarding the `NAME_MAPPING` constant, it was previously inside `Modalities`, but due to how `TextChoices` works, it was getting included in the `choices` property, which wasn’t ideal when referencing it. To fix this, I've moved it to the `Sample` model as an inner class, since it’s only relevant for that model. This approach keeps things simple, avoids adding extra helpers, and makes future cleanups easier if needed (as discussed in our meeting).
Let me know if you have any other suggestions or thoughts on this, thank you!
```py
In [1]: from scpca_portal.enums import Modalities
In [2]: Modalities.choices
Out[2]: 
[('BULK_RNA_SEQ', 'Bulk Rna Seq'),
('CITE_SEQ', 'Cite Seq'),
('MULTIPLEXED', …
```
> 1106 - Update classes in the enums folder to Enum subclasses

- api/scpca_portal/enums/__init__.py
- api/scpca_portal/enums/dataset_data_project_config.py
- api/scpca_portal/models/dataset.py
- api/scpca_portal/test/models/test_dataset.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1115
This PR introduced a `is_data_valid` property method, which leverages the `DataValidator` class to determine if the Dataset data attribute is properly build. The Dataset data attribute must contain a dictionary with keys being project_ids and values being config dictionaries which contain options and samples to draw from when querying for Original Files during Computed File generation.
A few tests were added to validate the project_id keys and config values confirm to the desired structure.
- test_dataset::test_is_data_valid_project_id
- test_dataset::test_is_data_valid_config
N/A
> 1115 - Add test_validate_data tests to test_dataset module

- api/scpca_portal/config/test.py
- api/scpca_portal/management/commands/dispatch_to_batch.py
- api/scpca_portal/models/job.py
- api/scpca_portal/test/management/commands/test_dispatch_to_batch.py
- api/scpca_portal/test/models/test_job.py
Closes #1117 
I've implemented the `Job::submit` method and added the corresponding test. 
Changes include: 
- Added a factory class method `get_job` 
- Included `django.utils.timezone.make_aware` in the test to prevent the the runtime warning below (matching the `sync_original_files` implementation)
- `RuntimeWarning: DateTimeField Job.submitted_at received a naive datetime `
**NOTE:** I encountered an issue when attempting to mock `datetime.datetime.now`. As a workaround, I checked the instance type of `submitted_at` after the job submission. Please let me know your thoughts. Thank you, David!
`test_job::test_submit_job`
N/A
> 1117 - Implement Job::submit method

- api/scpca_portal/models/job.py
- api/scpca_portal/test/factories.py
- api/scpca_portal/test/models/test_job.py
Close #1145
I've implement  the `Job::terminate` method and added the corresponding test using mocks. 
Additionally, I've added the `JobFactory` class and incorporated it in the `TestJob`, as well as cleaned up the no longer used attributes in the `JobTest::setUp` method.
- `TestJob::test_terminate_job`
- `TestJob::test_terminate_job_failure`
- `JobFactory`
N/A
> 1145 - Implement Job::terminate using the existing Job model instance

- api/scpca_portal/models/dataset.py
- api/scpca_portal/test/models/test_dataset.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1108.
This PR introduces an OriginalFile query on the Dataset model. This query is able to grab all of a Dataset's OriginalFiles based on its data and format attributes. A `test_original_files_property` test was also added, which verifies through different configurations that the behavior of the method is as expected.
- `test_original_files_property`
N/A
> 1108 - Dataset OriginalFile Query

- client/.storybook/stories/DatasetProjectCard.stories.js
- client/src/components/Badge.js
- client/src/components/DatasetProjectCard.js
- client/src/components/WarningText.js
- client/vercel.json
Closes #1157
Please see the latest Storybook [here](https://scpca-portal-963irvr6j-ccdl.vercel.app/?path=/story/components-datasetprojectcard--default).
I've implemented the `DatasetProjectCard` component and add the corresponding story with mock data in Storybook.
Other change include:
- Minor updates to the following components:
- Added a `children` prop to `Badge` 
- Moved the `children` prop outside of `Paragraph` in `WarningText` 
N/A
N/A
> 1157 - Add Dataset Project Card with Storybook

- api/scpca_portal/batch.py
- api/scpca_portal/models/job.py
- api/scpca_portal/test/factories.py
- api/scpca_portal/test/models/test_job.py
- api/scpca_portal/utils/helpers.py
Closes #1146
I've implemented the `Job::sync_state` instance method and `Job::bulk_sync_state` class method, and added the corresponding tests.
Other changes include:
- Added the `get_jobs` method to the `batch` module.
- Added `utils.get_chunk_list` for `boto3.describe_jobs` job ID size limit per request (I've used the solution from [Stack overflow: Split a list into equally-sized chunks](https://stackoverflow.com/a/312464), as using generators seems to be a commonly used approach. Please let me know if you have any other suggestions!)
- Defined `batch_job_id` using `factory.Sequence` and the default `batch_job_name` in `JobFactory`, and cleaned up `setUp` and no longer required arguments in `TestJob`
- …
> 1146 - Implement Job::sync_state and Job::bulk_sync_state methods using the existing Job model instance

- client/.storybook/stories/DatasetPortalWideDownloadCard.stories.js
- client/src/components/DatasetPortalWideDownloadCard.js
- client/vercel.json
Closes #1177
Please see the latest Storybook [here](https://scpca-portal-86ggp2vro-ccdl.vercel.app/?path=/story/components-datasetportalwidedownloadcard--projects-download).
I've implemented the `DatasetPortalWideDownloadCard` component and the corresponding Story using mock data.
There are two views added to the `DatasetPortalWideDownloadCard`story on Storybook:
- `Data Format` for the packaged projects download
- `Portal Metadata` for the portal-wide metadata download
N/A
N/A
> 1177 - Add Portal Wide Download Card with Storybook

- client/.storybook/stories/DatasetDownloadStarted.stories.js
- client/src/components/DatasetDownloadStarted.js
- client/src/components/Modal.js
- client/vercel.json
Closes #1178
Please see the latest Storybook [here](https://scpca-portal-kuphb1fs3-ccdl.vercel.app/?path=/story/components-datasetdownloadstarted--default).
I've implemented the `DatasetDownloadStarted` component and the corresponding Story using mock data.
Other changes include:
- Added a `titleNoBreakline` prop to the `Modal` component to prevent the modal `title` from wrapping
N/A
N/A
> 1178 - Add Download My Dataset for CCDL Dataset Downloading Modal Body with Storybook

- infrastructure/deploy.py
- infrastructure/deploy_modules/terraform.py
N/A
- When destroying an instance that doesnt have local .terraform, we need to be initialize the backend with backend_config args.
N/A
N/A
> destroy with init

- infrastructure/deploy.py
- infrastructure/deploy_modules/terraform.py
N/A
- removed redundant init code
- passes in tf_file_arg variable to both destroy and apply
- only init once but for any terraform action
N/A
N/A
> share args and backend_configs and init

- .github/workflows/deploy_staging_backend.yml
- infrastructure/deploy_modules/docker.py
N/A
- Removes Destroy Legacy (successfully taken down already)
- `subprocess.check_call` needs `shell=True` to take password via stdin / pipe
N/A Local login worked via sportal
N/A
> deploy docker stdin password

- api/scpca_portal/batch.py
- api/scpca_portal/management/commands/dispatch_to_batch.py
- api/scpca_portal/models/job.py
N/A
Jobs weren't able to be dispatched because of an extra empty string in the `batch.submit_job` `containerOverrides` `command` argument which AWS threw a fit over. This PR does the following.
- adds `--notify`  by extending the command list
- removes extraneous batch client from `dispatch_to_batch` management command
- fixes a copy paste typo from the submit job output when an error happens
Dev Stack
N/a
> fix job get project sample job

- client/src/components/DetailsTable.js
- client/src/components/EnvarBanner.js
- client/src/components/ProjectAbstractDetail.js
- client/src/components/Table.js
- client/src/pages/projects/[scpca_id].js
N/A
After the recent deploy I noticed that the client was throwing an error on the project page. This seems to be rooted in handling table instances that may or may not have pagination. This PR addresses that as well as some other rendering complaints by react.
- Fixes accessing `map` on undefined table `instance.page`
- Adds missing `key` prop to mapped renders
- Fixes `p > p` double nesting
N/A tested locally
> misc client fixes

- api/scpca_portal/models/dataset.py
- api/scpca_portal/serializers.py
- api/scpca_portal/test/models/test_dataset.py
- api/scpca_portal/test/utils/test_helpers.py
- api/scpca_portal/test/views/test_dataset.py
- api/scpca_portal/utils/helpers.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1226
This PR begins the implementation of the stats property. 
Five fields have been added in this PR:
- `current_data_hash`
- `current_readme_hash`
- `current_metadata_hash`
- `is_hash_changed`
- `uncompressed_size`
The remaining fields will be added in subsequent PRs.
- `test_dataset::test_uncompressed_size`
- `test_utils::TestConvertBytesToGB::test_converstion_successful`
> 1226 - Add Hashes and Uncompressed Size to Stats Property

- api/scpca_portal/management/commands/load_metadata.py
- api/scpca_portal/test/management/commands/test_load_metadata.py
Closes #1217
I've added a check to the `load_metadata` management command to verify that the `original_files` table has been populated. If it's empty, an error is raised with an instructive message to run the `sync_original_files` management command first.
- Updated `test_load_metadata`
N/A
> 1217 - Improve error message for missing OriginalFile in load_metadata management command

- api/scpca_portal/urls.py
N/A
We dont want to expose the dataset endpoint on prod yet.
This change will remove it on staging and dev environments as well. If you need access to it in a dev environment just comment it out until we have a better mechanism in place that only removes it on the deployer production environment.
N/A
N/A
> Remove dataset endpoint for prod envs

- api/scpca_portal/models/project.py
- api/scpca_portal/models/project_summary.py
- api/scpca_portal/test/expected_values/project_SCPCP999990.py
- api/scpca_portal/test/views/test_filter_options.py
Closes #1263
I've resolved the generation of invalid `seq_unit` and `technology` combinations for `summaries_counts`. 
- In `Project::update_project_aggregate_properties`, iterate through the libraries per sample to get each library's `seq_unit` and `technology` pair to:
- populate `summaries_counts`
- aggregate `seq_units` and `technologies` per project 
- Adjusted for the assertions for `seq_units` and `technologies` in `test.views.test_filter_options.FilterOptionsTestCase`
- Updated the docstring of the`ProjectSummary` model to reflect the changes
Updated:
- `test.views.test_filter_options.FilterOptionsTestCase`
N/A
> 1263 - Resolve invalid seq_unit and technology combinations in summaries_counts

- infrastructure/batch/compute_environment.tf
N/A
Encountering error with updating existing batch compute environments.
While trying to change the name of an old batch pipeline.
Error:
- `operation error Batch: DeleteComputeEnvironment`
- `ClientException: Cannot delete, found existing JobQueue relationship.`
Based on this comment: https://github.com/hashicorp/terraform-provider-aws/issues/13221#issuecomment-1692094916
This PR adds `create_before_destroy` to the batch compute environment resources in terraform.
N/A
N/A
> create before destroy

- infrastructure/batch/compute_environment.tf
- infrastructure/s3.tf
N/A
This PR fixes 2 issues with terraform:
When redeploying the ec2 compute environment AWS and terraform encountered an error.
`ClientException: Cannot delete, found existing JobQueue relationship.`
This can be resolved by setting a `create_before_destroy` lifecycle rule on the compute environment.
However, this will cause the following error:
`ClientException: Object already exists.`
This can be resolved by using `compute_environment_name_prefix` instead of just `compute_environment_name`.
Additionally, this PR resolves a warning that was related to a change in how s3 lifecycle configurations require a filter to be defined. So an empty one was added to stop that warning.
N/A Many local deployments to test.
N/A
> staging deploy compute environment

- api/scpca_portal/models/dataset.py
- api/scpca_portal/test/expected_values/dataset_custom_single_cell_experiment.py
- api/scpca_portal/test/expected_values/dataset_single_cell_ann_data_merged.py
- api/scpca_portal/test/expected_values/dataset_single_cell_ann_data_merged_SCPCP999990.py
- api/scpca_portal/test/expected_values/dataset_single_cell_single_cell_experiment_merged.py
- api/scpca_portal/test/expected_values/dataset_single_cell_single_cell_experiment_merged_SCPCP999990.py
- api/scpca_portal/test/models/test_computed_file.py
- api/scpca_portal/test/models/test_dataset.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1286.
In this PR, the merged single cell data attribute field directive is changed from an array of `["MERGED"]` to a string value of `"MERGED"`. Changes are made to the `DataValidator` class and during dataset instance instantiation, and corroborated in expected values files for testing.
N/A
N/A
> 1286 - Change Single Cell Merged Datatype

- api/scpca_portal/test/utils/test_helpers.py
- api/scpca_portal/utils/helpers.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1285.
In this PR, a `format_bytes` utils function was added. We wanted this method in order to be able to convert the int value off of `ComputedFile::size_in_bytes` to a formatted string rounded to two decimal places. 
Old byte conversion utils functions were removed as well.
- `test_format_bytes`
N/A
> 1285 - Add format bytes utils function

- api/scpca_portal/email_templates/dataset_ready.html
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1282.
In this PR, a `dataset_ready` email template was added. Included in this template thusfar are the header, the link button, and the footer. The main content, which includes a Dataset Summary table and a Download File Summary table, will be added in a future PR.
N/A
N/A
> 1282 - Start implementation of dataset_ready email template

- api/scpca_portal/common.py
- api/scpca_portal/models/dataset.py
- api/scpca_portal/models/job.py
- api/scpca_portal/test/models/test_job.py
Closes #1322 
- Added the `Job.apply_state` instance method for instance-level sync flow 
- Removed the now-obsolete `Job.set_state`
- Updated `Job` instance methods to use `Job.apply_state`
- **NOTE:** `Job.get_retry_job` now takes a `save` kwarg for bulk updates (called via `Job.create_retry_jobs`) 
- Updated `Dataset.apply_job_state` to accept a job instance
- Temporarily updated the soon-to-be-removed `Dataset` methods to align with the changes (prevent tests failures)
- Added a new test for `Job.apply_state` and updated relevant tests in `TestJob`
- Updated `TestJob` to reflect the changes
N/A
> 1322 - Add new Job.apply_state instance method for instance-level sync flow

- api/scpca_portal/management/commands/process_dataset.py
- api/scpca_portal/models/computed_file.py
- api/scpca_portal/models/job.py
- api/scpca_portal/test/models/test_computed_file.py
- api/scpca_portal/test/models/test_job.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1328.
In this PR, checks are made for lockfile and locked projects during processing, and should lockfile or locked projects be found, jobs are failed and cloned. The retry job then enters into the pending queue, to be dispatched at a later point.
- Additions and updates made to current tests to account for changes
N/A
> 1328 - Requeue locked jobs during processing

- api/scpca_portal/batch.py
- api/scpca_portal/exceptions.py
- api/scpca_portal/management/commands/process_dataset.py
- api/scpca_portal/models/job.py
- api/scpca_portal/test/models/test_job.py
Closes #1349
- In `Job` model:
- Renamed `get_retry_job` to `create_retry_job`
- Refactored instance methods and adjusted corresponding class methods for bulk operations:
- `submit` and `submit_pending`
- `terminate` and `terminate_processing`
- `sync_state` and `bulk_sync_state`
- In `exceptions`:
- Added new `JobError` subclasses: 
-  `JobSyncNotProcessingError`
-  `JobInvalidTerminateStateError`
-  `JobSyncStateFailedError`
-  `JobTerminationFailedError`
- Added `BatchError` and its subclass `BatchGetJobsFailedError`
- In `batch`:
- Refactor  `batch.get_jobs` to use `BatchGetJobsFailedError`
- Updated existing tests and added new one for exceptions in `TestJob`
Updated: 
- …
> 1349 - Add save kwarg to Job instance methods for bulk and instance-level updates

- .gitignore
- bin/sportal
- infrastructure/deploy.py
- infrastructure/deploy_modules/terraform.py
N/A
Encountered an issue yesterday where I realized we were unable to utilize certain debugging techniques on the portal.
This PR expands support of sportal with the following commands:
`sportal --sso profile_name deploy:init` - useful to quickly validate terraform syntax and configuration.
`sportal --sso profile_name deploy:console` - useful to enter a REPL and debug new or existing data structures.
`sportal --sso profile_name deploy:plan` - useful to see what terraform will do without running apply / deploy:up
`sportal --sso profile_name deploy:plan --save-plan` - useful for seeing what terraform will do and saving the output. This output can be seen with `terraform show infrastructure/PLAN`. To compare against a different terraform plan.
- New feature (non-breaking change which adds …
> Add support for sportal debug:init, debug:plan, and debug:console

- api/scpca_portal/migrations/0073_auto_20250604_1611.py
N/A
When migrating data types from strings to lists and dicts we didn't handle existing data in the database.
This PR updates the migration to drop those columns and re-create them.
Due to limitations of our implementation this migration will require re-loading everything on the portal which will take the portal offline for a few minutes while the new metadata is parsed and everything will be downloadable again within a couple hours.
N/A
N/A
> HOTFIX: blunt fix for existing data types

- api/scpca_portal/loader.py
- api/scpca_portal/management/commands/load_data.py
- api/scpca_portal/management/commands/load_metadata.py
- api/scpca_portal/metadata_parser.py
- api/scpca_portal/test/management/commands/test_create_ccdl_datasets.py
- api/scpca_portal/test/management/commands/test_create_portal_metadata.py
- api/scpca_portal/test/management/commands/test_load_data.py
- api/scpca_portal/test/management/commands/test_load_metadata.py
- api/scpca_portal/test/models/test_computed_file.py
- api/scpca_portal/test/models/test_dataset.py
- api/scpca_portal/test/test_loader.py
- api/scpca_portal/test/test_metadata_parser.py
Closes https://github.com/AlexsLemonade/scpca-portal/issues/1331.
- Remove the default value for `filter_on_project_ids` in `loader::get_projects_metadata`
- Remove the default value for `filter_on_project_ids` in `metadata_parser::load_projects_metadata`
- Bug fix: download `projects_metadata.csv` file in `metadata_parser::get_projects_metadata_ids` if file doesn't previously exist
N/A
N/A
> 1331 - Enforce filter_on_project_id usage in loader and metadata_parser

- api/scpca_portal/config/common.py
N/A
- Adds the config entry to remove `format` from default query parameters since we use this to specify data format with ComputedFiles and Datasets, and it collides with the response format option
N/A
N/A
> Hot Fix - Add URL format override none setting in rest_framework config

- api/scpca_portal/serializers/project.py
- api/scpca_portal/test/views/test_project.py
N/A
- To reduce the load time of /projects endpoint I want to test just serializing the metadata dataset when listing projects.
- Adds `Project.metadata_dataset` to the project serializer.
Note: This is not a complete change, we will want to also list out the Ids of the datasets and then fully serialize them on the detail of the project or just always show the ids.
N/A
N/A
> attach metadata dataset to project serializer

- api/scpca_portal/models/job.py
N/A
- when dispatching jobs, unable to iterate because after first submit we try to apply job state to dataset that does not exist, this PR fixes that
N/A
N/A
> Hotfix: only apply state if dataset exists

- api/scpca_portal/models/dataset.py
- api/scpca_portal/test/models/test_dataset.py
- api/scpca_portal/test/views/test_dataset.py
N/A 
Related PR: #1421 (which requires the changes included in this PR)
@davidsmejia, to get the downloadable samples counts and modality samples differences on each project card, I added the following new properties. I wasn't able to calculate these using the existing `dataset` fields on the client side (e.g., when single-cell samples are `"MERGED"`, no sample IDs are available in the API response) . Let me know what you think. Thank you! 
I've added the following properties to the `Dataset` model for the project card (`DatasetProjectCard`) on My Dataset page:
- ~~`project_modality_sample_difference`: a dict where the key is a project id in the dataset and the value is the number of samples that are unique to either the SINGLE_CELL or SPATIAL modality~~
e.g.) Data structure of this …
> Add project_modality_sample_difference and project_downloadable_sample_counts properties to Dataset

- .github/workflows/deploy_prod_backend.yml
- .github/workflows/deploy_staging_backend.yml
- bin/sportal
- infrastructure/deploy.py
- infrastructure/deploy_modules/terraform.py
- infrastructure/s3.tf
- infrastructure/variables.tf
#1445 
- Fixes some issues when locally testing changes for cellbrowser 
- Adds the cellbrowser bucket with a static site policy as well as limited permissions for uploading defined by a list of iam user ARNS
N/A tested with `sportal deploy:console` and `sportal deploy:plan`
N/A
> Add Cellbrowser Static Site Bucket

- client/src/components/DatasetProcessForm.js
- client/src/components/DatasetProcessModal.js
- client/src/contexts/DatasetManagerContext.js
- client/src/hooks/useDatasetManager.js
- client/src/pages/download/index.js
Closes #1406 
Stacked PR of #1455
@dvenprasad, see the latest UI Preview [here](https://scpca-portal-efo1qv6be-ccdl.vercel.app/). Thank you! 
I've added the support for initiating dataset download on My Dataset page.
- Added `DatasetProcessModal` for the `"Download Dataset"` modal, which initiates dataset processing for download
- Added `DatasetProcessForm`, which is rendered inside the modal and handles token generation and dataset submission
- Updated the `useDatasetManager.processDataset` method to directly use `myDataset` instead of accepting a dataset reference as an argument
- Renamed the localStorage state key for `email` to `dataset-email` in `DatasetManagerContext` for improved clarity
- Refactor (addresses code organization and design mentioned in corresponding …
> Add support for initiating dataset download via DatasetProcessModal

- infrastructure/s3.tf
#1445 
Adds missing closing curly brace from terraform in s3.
N/A
N/A
> add missing closing bracket

- api/scpca_portal/models/dataset.py
- api/scpca_portal/serializers/ccdl_dataset.py
N/A
- Removes the ability for ccdl datasets with spatial modality to falsely contain cite_seq projects (which is impossible)
- Exposes the entire related ComputedFile object on the CCDLDataset serializer list endpoint
- NOTE: this change is not necessary to make on the DatasetSerializer because there is no list endpoint on the DatasetSerializer, while the ComputeFile object is available on the DatasetSerializer retrieve endpoint.
N/A
N/A
> Remaining api changes to support portal wide datasets on client
